#!/bin/bash

echo "🚀 COMANDOS PARA EJECUTAR EN EL SERVIDOR"
echo "========================================"
echo ""
echo "# 1. SSH al servidor"
echo "ssh root@23.105.176.45"
echo "# Contraseña: gsiB%s@0yD"
echo ""
echo "# 2. Verificar configuración actual de nginx"
echo "grep -n 'client_max_body_size' /etc/nginx/sites-available/default"
echo ""
echo "# 3. Hacer backup de la configuración"
echo "cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup"
echo ""
echo "# 4. Editar configuración de nginx"
echo "nano /etc/nginx/sites-available/default"
echo ""
echo "# 5. AGREGAR/MODIFICAR estas líneas en el bloque server del puerto 8056:"
echo "#    En la sección de Directus, agregar:"
echo "#    client_max_body_size 5M;"
echo "#    proxy_read_timeout 300s;"
echo "#    proxy_connect_timeout 75s;"
echo ""
echo "# 6. Verificar sintaxis de nginx"
echo "nginx -t"
echo ""
echo "# 7. Recargar nginx"
echo "systemctl reload nginx"
echo ""
echo "# 8. Verificar que el servicio esté funcionando"
echo "systemctl status nginx"
echo ""
echo "# 9. Probar la conectividad"
echo "curl -k https://www.ultimamilla.com.ar:8056/server/ping"
echo ""
echo "# 10. Verificar logs si hay problemas"
echo "tail -f /var/log/nginx/error.log"
echo ""
echo "========================================"
echo "Después de estos pasos, ejecuta localmente:"
echo "python3 import-remaining-images.py"
echo "========================================" 