FROM node:20-alpine

WORKDIR /app

# Copiar archivos de dependencias primero para aprovechar la caché de Docker
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto de los archivos
COPY . .

# Exponer el puerto
EXPOSE 4321

# Variables de entorno - FORZAR PRODUCCION
ENV NODE_ENV=production
ENV ASTRO_TELEMETRY_DISABLED=1

# Build en tiempo de construcción de imagen
RUN npm run build

# Comando solo para producción
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0", "--port", "4321"]
