FROM node:20-alpine

WORKDIR /app

# Copiar archivos de dependencias primero para aprovechar la caché de Docker
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto de los archivos
COPY . .

# Exponer el puerto
EXPOSE 4321

# Variables de entorno
ENV NODE_ENV=production

# Comando para desarrollo o producción
CMD ["sh", "-c", "if [ '$NODE_ENV' = 'production' ]; then npm run build && npm run start -- --host 0.0.0.0 --port 4321; else npm run dev -- --host 0.0.0.0 --port 4321; fi"]
