services:
  database:
    image: postgres:15-alpine
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: directus
    volumes:
      - directus_db_data:/var/lib/postgresql/data
    networks:
      - directusnet

  directus-app:
    image: directus/directus:11.7.2
    container_name: directus-app
    environment:
      KEY: 12345678901234567890123456789012
      SECRET: S3cr3tK3yForDirectusConfig2025!!
      CORS_ENABLED: true
      CORS_ORIGIN: http://localhost:4321,http://23.105.176.45:8080
      SESSION_DOMAIN: localhost
      DB_CLIENT: pg
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: directus
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: adminpassword
      PUBLIC_DIRECTUS_URL: http://directus-app:8055
      PUBLIC_ROLE: public
      PUBLIC_ASSETS: true
      ASSETS_CACHE_TTL: "0"
      ASSETS_TRANSFORM_TOKEN_OPTIONAL: "true"
      DIRECTUS_STATIC_TOKEN: ${DIRECTUS_STATIC_TOKEN}
    depends_on:
      - database
    ports:
      - "8055:8055"
    volumes:
      - directus_uploads:/directus/uploads:Z
      - directus_extensions:/directus/extensions
    networks:
      - directusnet

  astro-app:
    build:
      context: .
      dockerfile: Dockerfile.astro.dev
    container_name: astro-app
    working_dir: /app
    ports:
      - "4321:4321"
    volumes:
      - .:/app
      # No montamos node_modules como volumen para evitar problemas de permisos
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - DIRECTUS_STATIC_TOKEN=${DIRECTUS_STATIC_TOKEN}
      - PUBLIC_DIRECTUS_URL=http://directus-app:8055
      - HOST=0.0.0.0
      - PORT=4321
    command: sh -c "npm install && npm run dev"
    depends_on:
      - directus-app
    networks:
      - directusnet

volumes:
  directus_db_data:
  directus_uploads:
  directus_extensions:
  astro_node_modules:

networks:
  directusnet:
