import {uid,stamp,parseDate} from './domain.mjs';
import {upgradeState,payCharges,monthlyDate,today,cents,syncLedger} from './finance.mjs';
export const responsible={id:'RESP-DEMO-01',name:'Elena Méndez',credential:'RESP-DEMO-01',role:'Responsable técnico ficticio'};
export const methods={card:'Tarjeta demo',qr:'QR demo',subscription:'Abono demo'};
export const providers={demo:'Pasarela de prueba',mercadopago:'Mercado Pago · sin conectar',payway:'Payway · sin conectar'};
export const PAYMENT_QR='UM DEMO SIN COBRO';
export function extendState(s){const n=upgradeState(s);return {...n,servicesVersion:1,demoDate:n.demoDate||today(),subscriptions:n.subscriptions||[],documents:n.documents||[],reports:n.reports||[],readAlerts:n.readAlerts||[]};}
export function changeDemoDate(s,value){if(parseDate(value)!==value||value<'2020-01-01'||value>'2100-12-31')throw Error('Elegí una fecha de prueba válida');return {...s,demoDate:value};}
export const daysBetween=(from,to)=>Math.round((new Date(to+'T12:00:00Z')-new Date(from+'T12:00:00Z'))/86400000);
export function subscriptionStatus(sub,day){const n=daysBetween(day,sub.nextDue);return n<0?'Abono vencido':n<=7?'Por vencer':'Abono al día';}
export function recordPayment(s,memberId,allocations,operationId,options={method:'card',provider:'demo'}){
 if(s.movements.some(m=>m.operationId===operationId))return s;
 if(!methods[options.method]||!providers[options.provider])throw Error('Elegí un medio y una plataforma de prueba');
 if(options.method==='subscription'){
  if(s.subscriptions.some(x=>x.memberId===memberId))throw Error('Este perfil ya tiene un abono. Usá tarjeta o QR demo para sus cuotas');
  if(allocations.some(a=>s.charges.find(c=>c.id===a.chargeId)?.kind!=='dues'))throw Error('El abono sólo se prepara desde cuotas originales');
  if(parseDate(options.nextDue)!==options.nextDue||options.nextDue<=s.demoDate||daysBetween(s.demoDate,options.nextDue)>90)throw Error('El próximo vencimiento debe ser posterior a la fecha de prueba y dentro de 90 días');
 }
 let n=payCharges(s,memberId,allocations,operationId);if(n===s)return s;const movement=n.movements[0],date=stamp();
 n={...n,movements:[{...movement,method:options.method,provider:options.provider,integration:'Simulación · plataforma sin conectar',demoDate:s.demoDate},...n.movements.slice(1)]};
 if(options.method==='subscription')n={...n,subscriptions:[{id:uid('ABO'),memberId,amountCents:movement.amountCents,nextDue:options.nextDue,created:date,operationId,history:[{date,note:'Abono mensual demo preparado. Sin débitos automáticos.'}]} ,...s.subscriptions]};
 n.subscriptions=n.subscriptions.map(sub=>{const renewal=n.charges.find(c=>c.subscriptionId===sub.id&&c.cycle===sub.nextDue);if(!renewal||renewal.paidCents<renewal.amountCents)return sub;return {...sub,nextDue:monthlyDate(sub.nextDue,1),history:[...sub.history,{date,note:`Renovación demo pagada: ${renewal.cycle}. No modifica la matrícula.`}]};});
 return n;
}
export function prepareRenewal(s,subscriptionId){const sub=s.subscriptions.find(x=>x.id===subscriptionId);if(!sub)throw Error('Abono no encontrado');if(daysBetween(s.demoDate,sub.nextDue)>7)throw Error('La renovación se habilita 7 días antes');const id=`REN-${sub.id}-${sub.nextDue}`;if(s.charges.some(c=>c.id===id))return s;return syncLedger({...s,charges:[...s.charges,{id,memberId:sub.memberId,label:'Renovación de abono',originalCents:sub.amountCents,amountCents:sub.amountCents,paidCents:0,status:'Pendiente',kind:'subscription',dueDate:sub.nextDue,subscriptionId:sub.id,cycle:sub.nextDue,planId:null,benefitId:null}]});}
export function getAlerts(s,memberId){const alerts=[];for(const sub of s.subscriptions.filter(x=>!memberId||x.memberId===memberId)){const diff=daysBetween(s.demoDate,sub.nextDue);if(diff<=7){const m=s.members.find(x=>x.id===sub.memberId);const id=`ABO:${sub.id}:${sub.nextDue}:${diff<0?'vencido':'proximo'}`;alerts.push({id,memberId:sub.memberId,type:'Abono',title:diff<0?'Tu abono está vencido':diff===0?'Tu abono vence hoy':`Tu abono vence en ${diff} días`,description:`${m?.name||'Perfil'} · Fecha ${sub.nextDue}. La matrícula legal no cambia.`,read:s.readAlerts.includes(id)});}}
 for(const m of s.members.filter(x=>!memberId||x.id===memberId)){if(m.validUntil&&daysBetween(s.demoDate,m.validUntil)<=30){const id=`MAT:${m.id}:${m.validUntil}`;alerts.push({id,memberId:m.id,type:'Matrícula declarada',title:daysBetween(s.demoDate,m.validUntil)<0?'Revisá la vigencia declarada de matrícula':'La vigencia declarada se aproxima',description:`${m.name} · Fecha declarada ${m.validUntil}. Consultá a la institución. Pagar no renueva la habilitación.`,read:s.readAlerts.includes(id)});}}
 return alerts;
}
export function markAlertsRead(s,ids){const allowed=new Set(getAlerts(s).map(x=>x.id));return {...s,readAlerts:[...new Set([...s.readAlerts,...ids.filter(x=>allowed.has(x))])].slice(-500)};}
export const MAX_DOCUMENT_BYTES=5*1024*1024;
export function inspectAttachment(bytes,name,mime){const b=bytes instanceof Uint8Array?bytes:new Uint8Array(bytes);if(!b.length||b.length>MAX_DOCUMENT_BYTES)throw Error('El archivo debe pesar entre 1 byte y 5 MB');let type;const ext=name.toLowerCase().split('.').at(-1);if(ext==='pdf'&&String.fromCharCode(...b.slice(0,5))==='%PDF-')type='application/pdf';else if(ext==='png'&&[137,80,78,71,13,10,26,10].every((n,i)=>b[i]===n)){if(b.length<24)throw Error('Imagen incompleta');const v=new DataView(b.buffer,b.byteOffset,b.byteLength),w=v.getUint32(16),h=v.getUint32(20);if(!w||!h||w*h>24000000||w>8000||h>8000)throw Error('La imagen excede 24 megapíxeles u 8.000 píxeles por lado');type='image/png';}else if(['jpg','jpeg'].includes(ext)&&b[0]===255&&b[1]===216&&b[2]===255){let pos=2;while(pos+9<b.length){if(b[pos]!==255){pos++;continue}const marker=b[pos+1];if([192,193,194,195,197,198,199,201,202,203,205,206,207].includes(marker)){const h=b[pos+5]*256+b[pos+6],w=b[pos+7]*256+b[pos+8];if(!w||!h||w*h>24000000||w>8000||h>8000)throw Error('La imagen excede el tamaño permitido');break}if(marker===216||marker===217){pos+=2;continue}const len=b[pos+2]*256+b[pos+3];if(len<2)break;pos+=len+2;}type='image/jpeg';}else throw Error('Usá un PDF, PNG o JPG válido. No se admiten SVG, HTML ni otros formatos');if(mime&&mime!=='application/octet-stream'&&mime!==type)throw Error('El contenido no coincide con el tipo de archivo');return {name:name.slice(0,180),size:b.byteLength,type};}
export function addDocument(s,memberId,kind,metadata,note,operationId){if(s.documents.some(d=>d.operationId===operationId))return s;if(!['Título','Matrícula'].includes(kind)||!s.members.some(m=>m.id===memberId))throw Error('Solicitud inválida');const date=stamp();return {...s,documents:[{id:uid('DOC'),memberId,kind,file:metadata,note:note.slice(0,800),version:1,status:'Pendiente',operationId,date,review:null,history:[{date,status:'Pendiente',note:'Documento ficticio presentado para revisión de demostración'}]},...s.documents]};}
export function reattachDocument(s,id,metadata){return {...s,documents:s.documents.map(d=>d.id===id?{...d,file:metadata,version:d.version+1,status:'Pendiente',review:null,history:[...d.history,{date:stamp(),status:'Pendiente',note:'Archivo reingresado. Se requiere una nueva revisión de esta versión.'}]}:d)};}
export function reviewDocument(s,id,status,observation,version,hasFile){const d=s.documents.find(d=>d.id===id);if(!d||d.version!==version)throw Error('El documento cambió. Volvé a abrirlo');if(!hasFile)throw Error('El archivo temporal no está disponible. Volvé a adjuntarlo antes de revisar');if(!['Aprobada demo','Rechazada demo'].includes(status)||observation.trim().length<5)throw Error('Agregá una observación de al menos 5 caracteres');if(d.review?.version===version&&d.review?.status===status&&d.review?.observation===observation.trim())return s;const review={status,observation:observation.trim().slice(0,600),date:stamp(),version,responsible};return {...s,documents:s.documents.map(x=>x.id===id?{...x,status,review,history:[...x.history,{date:review.date,status,note:review.observation+' · '+responsible.name+' · '+responsible.credential}]}:x)};}
export function saveReport(s,{id,memberId,title,body},operationId){if(title.trim().length<4||title.trim().length>120||body.trim().length<20||body.length>6000)throw Error('Completá un título de 4–120 caracteres y un informe de 20–6.000');const old=s.reports.find(r=>r.id===id);if(!old&&s.reports.some(r=>r.operationId===operationId))return s;if(old&&old.title===title.trim()&&old.body===body.trim())return s;const version=(old?.version||0)+1,date=stamp(),revision={version,title:title.trim(),body:body.trim(),date};const r={id:old?.id||uid('INF'),memberId:old?.memberId||memberId,title:revision.title,body:revision.body,version,status:'En revisión',approval:null,operationId:old?.operationId||operationId,date:old?.date||date,updated:date,revisions:[...(old?.revisions||[]),revision],history:[...(old?.history||[]),{date,status:'En revisión',note:old?.approval?`Versión ${version}: edición guardada. Aprobación de versión ${old.version} invalidada.`:`Versión ${version} guardada para revisión demo`}]};return {...s,reports:old?s.reports.map(x=>x.id===id?r:x):[r,...s.reports]};}
export function approveReport(s,id,version,operationId){const r=s.reports.find(r=>r.id===id);if(!r||r.version!==version)throw Error('El informe cambió. Revisá la versión actual');if(r.approval?.version===version)return s;const date=stamp(),approval={id:uid('APR'),version,date,responsible,operationId};return {...s,reports:s.reports.map(x=>x.id===id?{...x,status:'Aprobado demo',approval,history:[...x.history,{date,status:'Aprobado demo',note:`Versión ${version} aprobada por ${responsible.name} · ${responsible.credential}. Sin validez legal.`}]}:x)};}
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function reportHtml(r,member){const approved=r.approval?.version===r.version;return `<!doctype html><html lang="es"><meta charset="utf-8"><title>Informe de demostración</title><style>body{font:16px/1.6 Arial,sans-serif;max-width:850px;margin:40px auto;padding:25px;color:#172523}.mark{border:3px solid #bd352d;padding:18px;color:#9e2823;font-size:20px;font-weight:bold}h1{font-size:28px}pre{font:inherit;white-space:pre-wrap;overflow-wrap:anywhere}.approval{background:#eef3ed;padding:20px;border:1px solid #afc2ac}small{color:#53664e}@media print{@page{margin:30mm 18mm}.mark{position:fixed;top:-24mm;left:0;right:0;padding:8px;font-size:14px}body{margin:0;padding:0}body>small{position:fixed;bottom:-20mm}pre{orphans:3;widows:3}}</style><body><div class="mark">DEMOSTRACIÓN — sin validez legal</div><h1>${escape(r.title)}</h1><p>${escape(member?.name)} · ${escape(member?.license)}<br>Informe ${escape(r.id)} · Versión ${r.version}</p><pre>${escape(r.body)}</pre><div class="approval"><strong>${approved?'Aprobación de demostración registrada':'Sin aprobación vigente de esta versión'}</strong>${approved?`<p>Responsable ficticio: ${escape(r.approval.responsible.name)}<br>Credencial demo: ${escape(r.approval.responsible.credential)}<br>Fecha: ${escape(r.approval.date)}<br>Versión aprobada: ${r.approval.version}</p>`:'<p>Requiere revisión y aprobación de demostración.</p>'}</div><p>No es una firma digital certificada ni una certificación de autenticidad o habilitación profesional. No contiene firma manuscrita ni sello de autoridad.</p><small>Última Milla · Prototipo privado · Documento generado localmente</small></body></html>`;}
