import type { Antecedente, AntecedenteStatus, SectorSlug, ServiceCode } from "./types";

/**
 * 120 antecedentes operativos (mock) de ULTIMA MILLA S.A.
 * Distribución por sector (suma 120): aeropuertos 14, bodegas 16,
 * constructoras 13, gobierno 17, industria 15, mineria 10, salud 16,
 * seguridad-electronica 11, software 8.
 *
 * Los slugs se derivan automáticamente del título + id.
 */

const slugify = (s: string): string =>
  s
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

type AntecedenteSeed = Omit<Antecedente, "slug">;

const SEEDS: AntecedenteSeed[] = [
  // ───────────────────────── AEROPUERTOS (14) ─────────────────────────
  {
    id: 3001,
    title: "Cámara de CCTV - Aeropuerto de Mendoza",
    client: "Aeropuertos Argentina 2000",
    sectorSlug: "aeropuertos",
    serviceCodes: [102, 105],
    year: 2024, month: 3, location: "Mendoza City",
    scope: ["Instalación de 48 cámaras IP de alta resolución", "NVR con retención de 60 días", "Integración con centro de operaciones aeroportuario"],
    status: "verificado",
    image: "cctv-airport",
    summary: "Despliegue de circuito cerrado de televisión IP en terminal de pasajeros y zona de equipajes del Aeropuerto El Plumerillo.",
    tags: ["CCTV", "Aeroportuario", "Seguridad"],
  },
  {
    id: 3002,
    title: "Implementación de Redes de Datos y Fibra Óptica - Aeropuertos Argentina 2000",
    client: "Aeropuertos Argentina 2000",
    sectorSlug: "aeropuertos",
    serviceCodes: [101, 103],
    year: 2022, month: 9, location: "Mendoza City",
    scope: ["Tendido de 12 km de fibra óptica monomodo", "Certificación de enlaces con OTDR", "Migración en caliente sin corte de servicio"],
    status: "verificado",
    image: "fiber-optic",
    summary: "Backbone de fibra óptica certificada entre terminal, torre de control y hangares del aeropuerto.",
    tags: ["Fibra óptica", "Redes", "Aeroportuario"],
  },
  {
    id: 3003,
    title: "Sistema de Detección de Incendios - Aeropuerto El Plumerillo",
    client: "Aeropuertos Argentina 2000",
    sectorSlug: "aeropuertos",
    serviceCodes: [107, 105],
    year: 2023, month: 5, location: "Mendoza City",
    scope: ["Diseño según normas IRAM y NFPA", "Detectores de humo y llama en terminal", "Integración con sistema de evacuación"],
    status: "verificado",
    image: "fire-detection",
    summary: "Sistema SDI certificado para terminal de pasajeros y zonas críticas del aeropuerto.",
    tags: ["SDI", "Aeroportuario", "Seguridad"],
  },
  {
    id: 3004,
    title: "Mantenimiento Crítico de Sistemas de Detección - Aeropuerto de San Juan",
    client: "Aeropuertos Argentina 2000",
    sectorSlug: "aeropuertos",
    serviceCodes: [107, 105],
    year: 2024, month: 11, location: "San Juan",
    scope: ["Mantenimiento preventivo programado", "Pruebas de detectores y pulsadores", "Protocolo de response 24/7"],
    status: "operativo",
    image: "fire-detection",
    summary: "Plan de mantenimiento crítico para el sistema SDI del aeropuerto sanjuanino.",
    tags: ["SDI", "Mantenimiento", "Aeroportuario"],
  },
  {
    id: 3005,
    title: "Infraestructura de Red para Torres de Control - AeroControl SA",
    client: "AeroControl SA",
    sectorSlug: "aeropuertos",
    serviceCodes: [101, 108],
    year: 2023, month: 2, location: "Mendoza City",
    scope: ["Topología redundante con failover automático", "Cableado estructurado certificado categoría 6A", "Tablero IT con UPS de autonomía extendida"],
    status: "verificado",
    image: "control-room",
    summary: "Redundancia total para el sistema de comunicaciones de torre de control aeroportuaria.",
    tags: ["Redes", "Eléctricos IT", "Aeroportuario"],
  },
  {
    id: 3006,
    title: "Cableado Estructurado en Terminal de Pasajeros - Aeropuerto de Malargüe",
    client: "Aeropuertos Argentina 2000",
    sectorSlug: "aeropuertos",
    serviceCodes: [101, 108],
    year: 2021, month: 7, location: "Malargüe",
    scope: ["Cableado categoría 6A certificado", "Patch panels y racks organizados", "Documentación completa entregada"],
    status: "operativo",
    image: "network-cabinet",
    summary: "Cableado estructurado completo para la ampliación del terminal de Malargüe.",
    tags: ["Cableado estructurado", "Redes", "Aeroportuario"],
  },
  {
    id: 3007,
    title: "Soporte IT 24/7 para Operaciones Aeronáuticas - Aerolíneas del Sur",
    client: "Aerolíneas del Sur",
    sectorSlug: "aeropuertos",
    serviceCodes: [105, 106],
    year: 2025, month: 1, location: "Mendoza City",
    scope: ["Mesa de ayuda con SLA de 2 horas", "Monitoreo proactivo de infraestructura", "Reportes mensuales de disponibilidad"],
    status: "operativo",
    image: "server-room",
    summary: "Servicio de soporte 24/7 con SLA garantizado para la operación aeronáutica.",
    tags: ["Soporte 24/7", "Consultoría IT", "Aeroportuario"],
  },
  {
    id: 3008,
    title: "Cámaras IP de Perímetro para Aeropuerto - Aeropuertos Andinos",
    client: "Aeropuertos Andinos",
    sectorSlug: "aeropuertos",
    serviceCodes: [102, 105],
    year: 2024, month: 6, location: "San Juan",
    scope: ["Cámaras IP con analítica de video (LPR)", "Cobertura de perímetro de 4 km", "Detección de intrusión inteligente"],
    status: "verificado",
    image: "cctv-perimeter",
    summary: "Vigilancia perimetral con analítica de video y reconocimiento de patentes para el aeropuerto.",
    tags: ["CCTV", "Analítica de video", "Aeroportuario"],
  },
  {
    id: 3009,
    title: "Consultoría IT en Seguridad Aeroportuaria - Dirección de Aeronáutica Civil",
    client: "Dirección de Aeronáutica Civil",
    sectorSlug: "aeropuertos",
    serviceCodes: [106, 102],
    year: 2023, month: 10, location: "Mendoza City",
    scope: ["Auditoría de infraestructura existente", "Plan de mejora por fases", "Acompañamiento técnico en licitaciones"],
    status: "verificado",
    image: "consulting-board",
    summary: "Auditoría y plan de modernización para la infraestructura de seguridad aeroportuaria regional.",
    tags: ["Consultoría IT", "Seguridad", "Aeroportuario"],
  },
  {
    id: 3010,
    title: "Instalación Eléctrica para Sala de Equipajes - Aeropuerto de Mendoza",
    client: "Aeropuertos Argentina 2000",
    sectorSlug: "aeropuertos",
    serviceCodes: [108, 101],
    year: 2022, month: 4, location: "Mendoza City",
    scope: ["Tablero eléctrico de uso IT con selectividad", "UPS con autonomía dimensionada", "Sistema de tierra dedicada"],
    status: "operativo",
    image: "electrical-panel",
    summary: "Instalación eléctrica crítica para el sistema de handling de equipajes.",
    tags: ["Eléctricos IT", "Redes", "Aeroportuario"],
  },
  {
    id: 3011,
    title: "Redes WiFi de Alta Densidad para Terminal - Aeropuertos Argentina 2000",
    client: "Aeropuertos Argentina 2000",
    sectorSlug: "aeropuertos",
    serviceCodes: [101, 103],
    year: 2024, month: 8, location: "Mendoza City",
    scope: ["Despliegue de 80 access points WiFi 6", "Gestión centralizada de roaming", "Portal cautivo con autenticación"],
    status: "verificado",
    image: "wifi-terminal",
    summary: "Red WiFi de alta densidad para 4.000 pasajeros simultáneos en el terminal.",
    tags: ["WiFi", "Redes", "Aeroportuario"],
  },
  {
    id: 3012,
    title: "Mantenimiento de Sistemas SDI - Aeropuerto de San Luis",
    client: "Aeropuertos Argentina 2000",
    sectorSlug: "aeropuertos",
    serviceCodes: [107, 105],
    year: 2023, month: 12, location: "San Luis",
    scope: ["Mantenimiento preventivo trimestral", "Pruebas de pulsadores y detectores", "Reportes de cumplimiento normativo"],
    status: "mantenimiento",
    image: "fire-detection",
    summary: "Plan trimestral de mantenimiento del sistema SDI en aeropuerto puntano.",
    tags: ["SDI", "Mantenimiento", "Aeroportuario"],
  },
  {
    id: 3013,
    title: "Centro de Monitoreo de CCTV Aeroportuario - AeroHub Mendoza",
    client: "AeroHub Mendoza",
    sectorSlug: "aeropuertos",
    serviceCodes: [102, 105],
    year: 2025, month: 2, location: "Mendoza City",
    scope: ["Diseño de centro de operaciones 24/7", "Integración PSIM multisede", "Operadores capacitados"],
    status: "operativo",
    image: "control-room",
    summary: "Centro de operaciones unificado para monitoreo de CCTV y seguridad aeroportuaria.",
    tags: ["Centro de monitoreo", "CCTV", "Aeroportuario"],
  },
  {
    id: 3014,
    title: "Sistema de Detección en Hangares - Aeropuerto El Plumerillo",
    client: "Aeropuertos Argentina 2000",
    sectorSlug: "aeropuertos",
    serviceCodes: [107, 105],
    year: 2022, month: 6, location: "Mendoza City",
    scope: ["Detectores lineales de humo para hangares", "Pulsadores manuales y alarmas sonoras", "Integración con extinción por gas"],
    status: "verificado",
    image: "fire-detection",
    summary: "Sistema de detección de incendios para hangares de mantenimiento de aeronaves.",
    tags: ["SDI", "Aeroportuario", "Hangares"],
  },

  // ───────────────────────── BODEGAS (16) ─────────────────────────
  {
    id: 3015,
    title: "Desarrollo de Software y Digitalización de Procesos para Bodega Andeluna",
    client: "Bodega Andeluna",
    sectorSlug: "bodegas",
    serviceCodes: [104, 106],
    year: 2024, month: 4, location: "Tupungato",
    scope: ["Levantamiento de requisitos con enólogos y producción", "Desarrollo ágil con sprints quincenales", "Capacitación de usuarios finales"],
    status: "verificado",
    image: "software-screen",
    summary: "Plataforma de gestión de cosecha y trazabilidad vitivinícola end-to-end para bodega premium.",
    tags: ["Software", "Trazabilidad", "Vitivinícola"],
  },
  {
    id: 3016,
    title: "Implementación de Redes de Datos y Fibra Óptica - Bodega Tapiz",
    client: "Bodega Tapiz",
    sectorSlug: "bodegas",
    serviceCodes: [101, 103],
    year: 2023, month: 3, location: "Maipú",
    scope: ["Fibra óptica entre cava, sala de frío y oficina", "Certificación de enlaces categoría 6A", "Segmentación de VLAN por área"],
    status: "verificado",
    image: "fiber-optic",
    summary: "Backbone de fibra óptica que une las áreas productivas y administrativas de la bodega.",
    tags: ["Fibra óptica", "Redes", "Vitivinícola"],
  },
  {
    id: 3017,
    title: "Cámaras de CCTV IP para Bodega Septima",
    client: "Bodega Septima",
    sectorSlug: "bodegas",
    serviceCodes: [102, 105],
    year: 2024, month: 9, location: "Agrelo",
    scope: ["Cámaras IP en cava y sala de barricas", "Visualización remota desde la app", "Notificaciones de movimiento"],
    status: "operativo",
    image: "cctv-cellar",
    summary: "Sistema de CCTV IP para control de calidad y seguridad de la cava.",
    tags: ["CCTV", "Vitivinícola", "Seguridad"],
  },
  {
    id: 3018,
    title: "Sistema de Detección de Incendios en Cava - Bodega Norton",
    client: "Bodega Norton",
    sectorSlug: "bodegas",
    serviceCodes: [107, 105],
    year: 2022, month: 11, location: "Luján de Cuyo",
    scope: ["Detectores de humo aspirantes para cava", "Cumplimiento de normas IRAM", "Pruebas trimestrales"],
    status: "verificado",
    image: "fire-detection",
    summary: "Sistema SDI aspirante para la cava de barricas de bodega histórica.",
    tags: ["SDI", "Vitivinícola", "Cava"],
  },
  {
    id: 3019,
    title: "Cableado Estructurado en Sala de Frío - Bodega Salentein",
    client: "Bodega Salentein",
    sectorSlug: "bodegas",
    serviceCodes: [101, 108],
    year: 2023, month: 1, location: "Tupungato",
    scope: ["Cableado categoría 6A certificado", "Racks sellados para ambiente frío", "Tablero eléctrico dedicado"],
    status: "operativo",
    image: "network-cabinet",
    summary: "Infraestructura de red y energía para la sala de frío de bodega de altura.",
    tags: ["Cableado estructurado", "Eléctricos IT", "Vitivinícola"],
  },
  {
    id: 3020,
    title: "Mantenimiento Crítico de Redes - Bodega Catena del Sur",
    client: "Bodega Catena del Sur",
    sectorSlug: "bodegas",
    serviceCodes: [101, 105],
    year: 2024, month: 7, location: "Agrelo",
    scope: ["Monitoreo proactivo de switches", "Parcheos de seguridad programados", "Reportes mensuales de SLA"],
    status: "mantenimiento",
    image: "server-room",
    summary: "Servicio de mantenimiento preventivo y correctivo para la red productiva de la bodega.",
    tags: ["Mantenimiento", "Redes", "Vitivinícola"],
  },
  {
    id: 3021,
    title: "Infraestructura IT para Planta de Embotellado - Bodega Frontera",
    client: "Bodega Frontera",
    sectorSlug: "bodegas",
    serviceCodes: [101, 108],
    year: 2022, month: 5, location: "San Martín",
    scope: ["Redes industriales tolerantes a fallas", "Tableros IT para línea de embotellado", "Telemetría de energía en tiempo real"],
    status: "verificado",
    image: "factory-floor",
    summary: "Infraestructura de red y energía para la nueva línea de embotellado de alta velocidad.",
    tags: ["Redes industriales", "Eléctricos IT", "Vitivinícola"],
  },
  {
    id: 3022,
    title: "Soporte IT 24/7 para Operaciones de Cosecha - Bodega Andeluna",
    client: "Bodega Andeluna",
    sectorSlug: "bodegas",
    serviceCodes: [105, 106],
    year: 2025, month: 2, location: "Tupungato",
    scope: ["Mesa de ayuda prioritaria durante cosecha", "Técnico onsite rotativo", "Monitoreo 24/7 de infraestructura"],
    status: "operativo",
    image: "vineyard-cellar",
    summary: "Servicio intensivo de soporte durante la ventana crítica de cosecha.",
    tags: ["Soporte 24/7", "Consultoría IT", "Cosecha"],
  },
  {
    id: 3023,
    title: "Consultoría IT en Trazabilidad Vitivinícola - Bodega Trapiche Sur",
    client: "Bodega Trapiche Sur",
    sectorSlug: "bodegas",
    serviceCodes: [106, 104],
    year: 2023, month: 8, location: "Maipú",
    scope: ["Diagnóstico de procesos manuales", "Propuesta de digitalización por fases", "Roadmap de transformación"],
    status: "verificado",
    image: "consulting-board",
    summary: "Plan de modernización de la trazabilidad desde el viñedo hasta la botella.",
    tags: ["Consultoría IT", "Trazabilidad", "Vitivinícola"],
  },
  {
    id: 3024,
    title: "Desarrollo de Software de Gestión de Stock - Bodega Margen Sur",
    client: "Bodega Margen Sur",
    sectorSlug: "bodegas",
    serviceCodes: [104, 106],
    year: 2024, month: 10, location: "San Rafael",
    scope: ["Aplicación web con roles y permisos", "Integración con balanzas y lectores RFID", "Dashboard en tiempo real"],
    status: "operativo",
    image: "software-screen",
    summary: "Sistema a medida para el control de stock de insumos y producto terminado.",
    tags: ["Software", "RFID", "Vitivinícola"],
  },
  {
    id: 3025,
    title: "Cámaras IP para Control de Calidad - Bodega Renacer",
    client: "Bodega Renacer",
    sectorSlug: "bodegas",
    serviceCodes: [102, 105],
    year: 2023, month: 6, location: "Luján de Cuyo",
    scope: ["Cámaras IP en línea de embotellado", "Analítica de video para conteo", "Alertas de anomalías"],
    status: "verificado",
    image: "cctv-camera",
    summary: "Sistema de visión artificial para control de calidad en línea de embotellado.",
    tags: ["CCTV", "Analítica de video", "Vitivinícola"],
  },
  {
    id: 3026,
    title: "Sistema SDI en Sala de Barricas - Bodega Mendel",
    client: "Bodega Mendel",
    sectorSlug: "bodegas",
    serviceCodes: [107, 105],
    year: 2022, month: 2, location: "Luján de Cuyo",
    scope: ["Detectores de humo aspirantes", "Pulsadores y alarmas sonoras", "Protocolo de evacuación"],
    status: "verificado",
    image: "fire-detection",
    summary: "Sistema SDI para la sala de barricas con cumplimiento de normas IRAM.",
    tags: ["SDI", "Vitivinícola", "Cava"],
  },
  {
    id: 3027,
    title: "Instalación Eléctrica para Data Center de Bodega - Bodega Tapiz",
    client: "Bodega Tapiz",
    sectorSlug: "bodegas",
    serviceCodes: [108, 101],
    year: 2024, month: 12, location: "Maipú",
    scope: ["Tablero IT con selectividad", "UPS con autonomía de 30 minutos", "Sistema de tierra dedicada"],
    status: "operativo",
    image: "electrical-panel",
    summary: "Instalación eléctrica para el nuevo data center de la bodega.",
    tags: ["Eléctricos IT", "Data Center", "Vitivinícola"],
  },
  {
    id: 3028,
    title: "Redes Industriales para Planta de Embarque - Bodega Zuccardi Sur",
    client: "Bodega Zuccardi Sur",
    sectorSlug: "bodegas",
    serviceCodes: [101, 103],
    year: 2023, month: 11, location: "San Martín",
    scope: ["Redes industriales con switches ruggedizados", "Fibra óptica entre playas de cargas", "Segmentación por área productiva"],
    status: "verificado",
    image: "factory-floor",
    summary: "Red industrial para la playa de embarque de la bodega de alta producción.",
    tags: ["Redes industriales", "Fibra óptica", "Vitivinícola"],
  },
  {
    id: 3029,
    title: "Detección de Incendios en Depósitos - Bodega Luigi Bosca Sur",
    client: "Bodega Luigi Bosca Sur",
    sectorSlug: "bodegas",
    serviceCodes: [107, 105],
    year: 2025, month: 3, location: "Maipú",
    scope: ["Detectores de humo y temperatura", "Sirenas y balizas multisede", "Mantenimiento trimestral"],
    status: "operativo",
    image: "fire-detection",
    summary: "Sistema SDI multisede para los depósitos de insumos y producto terminado.",
    tags: ["SDI", "Vitivinícola", "Depósitos"],
  },
  {
    id: 3030,
    title: "Monitoreo Remoto de Tanques de Fermentación - Bodega Alta Vista",
    client: "Bodega Alta Vista",
    sectorSlug: "bodegas",
    serviceCodes: [101, 104],
    year: 2024, month: 5, location: "Agrelo",
    scope: ["Sensores IoT de temperatura y densidad", "Plataforma web con dashboards", "Alertas configurables por umbral"],
    status: "verificado",
    image: "vineyard-cellar",
    summary: "Monitoreo remoto de tanques de fermentación con telemetría en tiempo real.",
    tags: ["IoT", "Software", "Vitivinícola"],
  },

  // ───────────────────────── CONSTRUCTORAS (13) ─────────────────────────
  {
    id: 3031,
    title: "Instalación Eléctrica para Data Center - Constructora Cuyo",
    client: "Constructora Cuyo",
    sectorSlug: "constructoras",
    serviceCodes: [108, 101],
    year: 2023, month: 4, location: "Mendoza City",
    scope: ["Tablero IT con selectividad total", "UPS con autonomía de 60 minutos", "Sistema de tierra dedicada"],
    status: "verificado",
    image: "electrical-panel",
    summary: "Instalación eléctrica crítica para el data center del edificio corporativo.",
    tags: ["Eléctricos IT", "Data Center", "Constructora"],
  },
  {
    id: 3032,
    title: "Mantenimiento Crítico de Sistemas de Detección - TORRE THAYS",
    client: "Torre Thays",
    sectorSlug: "constructoras",
    serviceCodes: [107, 105],
    year: 2024, month: 1, location: "Mendoza City",
    scope: ["Mantenimiento preventivo programado", "Pruebas de detectores y pulsadores", "Protocolo de response 24/7"],
    status: "verificado",
    image: "fire-detection",
    summary: "Plan de mantenimiento crítico del sistema SDI en torre residencial premium.",
    tags: ["SDI", "Mantenimiento", "Torre"],
  },
  {
    id: 3033,
    title: "Cableado Estructurado en Edificio Corporativo - Constructora Sur Andina",
    client: "Constructora Sur Andina",
    sectorSlug: "constructoras",
    serviceCodes: [101, 108],
    year: 2022, month: 8, location: "Mendoza City",
    scope: ["Cableado categoría 6A certificado", "Patch panels y racks organizados", "Documentación completa entregada"],
    status: "operativo",
    image: "network-cabinet",
    summary: "Cableado estructurado completo para edificio corporativo de 12 pisos.",
    tags: ["Cableado estructurado", "Redes", "Constructora"],
  },
  {
    id: 3034,
    title: "Sistema de Detección de Incendios en Torre Residencial - Consorcio Edificio Plaza",
    client: "Consorcio Edificio Plaza",
    sectorSlug: "constructoras",
    serviceCodes: [107, 105],
    year: 2023, month: 9, location: "Mendoza City",
    scope: ["Diseño según normas IRAM y NFPA", "Detectores en cada unidad funcional", "Integración con sistema de evacuación"],
    status: "verificado",
    image: "fire-detection",
    summary: "Sistema SDI certificado para torre residencial de 20 pisos.",
    tags: ["SDI", "Torre", "Constructora"],
  },
  {
    id: 3035,
    title: "Cámaras de CCTV IP para Obra - Constructora Mendocina",
    client: "Constructora Mendocina",
    sectorSlug: "constructoras",
    serviceCodes: [102, 105],
    year: 2024, month: 6, location: "Mendoza City",
    scope: ["Cámaras IP móviles con conexión 4G", "Monitoreo remoto desde central", "Grabación con retención configurable"],
    status: "operativo",
    image: "cctv-camera",
    summary: "Sistema de CCTV para el control de seguridad y avance de obra.",
    tags: ["CCTV", "Obra", "Constructora"],
  },
  {
    id: 3036,
    title: "Implementación de Redes para Edificio Inteligente - Torre Thays",
    client: "Torre Thays",
    sectorSlug: "constructoras",
    serviceCodes: [101, 102],
    year: 2023, month: 7, location: "Mendoza City",
    scope: ["Red convergente voz/datos/seguridad", "Integración con sistema BMS", "Control de accesos por piso"],
    status: "verificado",
    image: "smart-building",
    summary: "Infraestructura de red para torre con sistema de edificio inteligente.",
    tags: ["Redes", "Edificio inteligente", "Torre"],
  },
  {
    id: 3037,
    title: "Soporte IT para Oficina Técnica - Constructora Andina",
    client: "Constructora Andina",
    sectorSlug: "constructoras",
    serviceCodes: [105, 106],
    year: 2025, month: 2, location: "Mendoza City",
    scope: ["Mesa de ayuda con SLA de 4 horas", "Soporte a usuarios en obra", "Mantenimiento de estaciones de diseño"],
    status: "operativo",
    image: "server-room",
    summary: "Servicio de soporte IT para la oficina técnica y estaciones de CAD/BIM.",
    tags: ["Soporte 24/7", "Consultoría IT", "Constructora"],
  },
  {
    id: 3038,
    title: "Infraestructura Eléctrica IT en Data Center - Constructora del Plata",
    client: "Constructora del Plata",
    sectorSlug: "constructoras",
    serviceCodes: [108, 101],
    year: 2022, month: 10, location: "Mendoza City",
    scope: ["Tableros IT con selectividad total", "Grupos electrógenos de respaldo", "Telemetría de energía en tiempo real"],
    status: "verificado",
    image: "datacenter",
    summary: "Infraestructura eléctrica completa para el data center de edificio corporativo.",
    tags: ["Eléctricos IT", "Data Center", "Constructora"],
  },
  {
    id: 3039,
    title: "Consultoría IT en Edificios Inteligentes - Consorcio Edificio Plaza",
    client: "Consorcio Edificio Plaza",
    sectorSlug: "constructoras",
    serviceCodes: [106, 101],
    year: 2024, month: 3, location: "Mendoza City",
    scope: ["Auditoría de infraestructura existente", "Plan de modernización por fases", "Definición de stack tecnológico"],
    status: "verificado",
    image: "consulting-board",
    summary: "Consultoría para la modernización inteligente del edificio.",
    tags: ["Consultoría IT", "Edificio inteligente", "Constructora"],
  },
  {
    id: 3040,
    title: "Sistema de Seguridad Electrónica en Obra - Constructora Cuyo",
    client: "Constructora Cuyo",
    sectorSlug: "constructoras",
    serviceCodes: [102, 105],
    year: 2023, month: 5, location: "Mendoza City",
    scope: ["Control de accesos para personal de obra", "CCTV en zonas críticas", "Reportes de asistencia"],
    status: "operativo",
    image: "cctv-camera",
    summary: "Sistema integral de seguridad electrónica para sitio de obra en construcción.",
    tags: ["CCTV", "Control de accesos", "Obra"],
  },
  {
    id: 3041,
    title: "Detección de Incendios en Garajes Subterráneos - Torre Thays",
    client: "Torre Thays",
    sectorSlug: "constructoras",
    serviceCodes: [107, 105],
    year: 2024, month: 11, location: "Mendoza City",
    scope: ["Detectores lineales de humo en cochera", "Sirenas y balizas multisede", "Integración con extracción de humos"],
    status: "verificado",
    image: "fire-detection",
    summary: "Sistema SDI para los garajes subterráneos de la torre.",
    tags: ["SDI", "Garajes", "Torre"],
  },
  {
    id: 3042,
    title: "Cableado de Fibra Óptica en Edificios - Constructora Mendocina",
    client: "Constructora Mendocina",
    sectorSlug: "constructoras",
    serviceCodes: [101, 103],
    year: 2022, month: 3, location: "Mendoza City",
    scope: ["Fibra óptica por columna montante", "Certificación de enlaces con OTDR", "Empalmes y conectores fusionados"],
    status: "operativo",
    image: "fiber-optic",
    summary: "Backbone de fibra óptica vertical para edificio corporativo de 15 pisos.",
    tags: ["Fibra óptica", "Redes", "Constructora"],
  },
  {
    id: 3043,
    title: "Mantenimiento de CCTV en Edificios - Consorcio Edificio Plaza",
    client: "Consorcio Edificio Plaza",
    sectorSlug: "constructoras",
    serviceCodes: [102, 105],
    year: 2025, month: 4, location: "Mendoza City",
    scope: ["Limpieza y calibración de cámaras", "Actualización de firmware del NVR", "Reemplazo de discos de grabación"],
    status: "mantenimiento",
    image: "cctv-camera",
    summary: "Servicio de mantenimiento preventivo para el sistema de CCTV del edificio.",
    tags: ["Mantenimiento", "CCTV", "Constructora"],
  },

  // ───────────────────────── GOBIERNO (17) ─────────────────────────
  {
    id: 3044,
    title: "Desarrollo de Software y Digitalización de Procesos para el Gobierno de la Provincia de Mendoza",
    client: "Gobierno de la Provincia de Mendoza",
    sectorSlug: "gobierno",
    serviceCodes: [104, 106],
    year: 2024, month: 6, location: "Mendoza City",
    scope: ["Levantamiento de procesos en 12 ministerios", "Desarrollo ágil con sprints quincenales", "Capacitación a 800 usuarios"],
    status: "verificado",
    image: "software-screen",
    summary: "Plataforma de digitalización de trámites para la administración pública provincial.",
    tags: ["Software", "Modernización del Estado", "Gobierno"],
  },
  {
    id: 3045,
    title: "Soporte de Infraestructura IT de Alta Disponibilidad - Municipalidad Guaymallén",
    client: "Municipalidad de Guaymallén",
    sectorSlug: "gobierno",
    serviceCodes: [105, 106],
    year: 2023, month: 5, location: "Guaymallén",
    scope: ["Mesa de ayuda 24/7 con SLA medible", "Monitoreo proactivo de data center", "Reportes mensuales de disponibilidad"],
    status: "verificado",
    image: "server-room",
    summary: "Soporte IT de alta disponibilidad para el data center municipal.",
    tags: ["Soporte 24/7", "Consultoría IT", "Gobierno"],
  },
  {
    id: 3046,
    title: "Implementación de Redes de Datos - Municipalidad de Las Heras",
    client: "Municipalidad de Las Heras",
    sectorSlug: "gobierno",
    serviceCodes: [101, 105],
    year: 2024, month: 9, location: "Las Heras",
    scope: ["Cableado estructurado en sedes descentralizadas", "VPN site-to-site con cifrado", "Segmentación de tráfico administrativo"],
    status: "verificado",
    image: "network-cabinet",
    summary: "Red de datos que interconecta sedes municipales descentralizadas.",
    tags: ["Redes", "Soporte 24/7", "Gobierno"],
  },
  {
    id: 3047,
    title: "Cámaras de CCTV IP para Seguridad Ciudadana - Municipalidad de Godoy Cruz",
    client: "Municipalidad de Godoy Cruz",
    sectorSlug: "gobierno",
    serviceCodes: [102, 105],
    year: 2023, month: 8, location: "Godoy Cruz",
    scope: ["Cámaras IP de alta resolución en espacios públicos", "Centro de monitoreo 24/7", "Integración con comisarías"],
    status: "verificado",
    image: "cctv-camera",
    summary: "Red de cámaras IP para el sistema de seguridad ciudadana municipal.",
    tags: ["CCTV", "Seguridad ciudadana", "Gobierno"],
  },
  {
    id: 3048,
    title: "Sistema de Detección en Edificios Públicos - Ministerio de Hacienda Mendoza",
    client: "Ministerio de Hacienda Mendoza",
    sectorSlug: "gobierno",
    serviceCodes: [107, 105],
    year: 2022, month: 11, location: "Mendoza City",
    scope: ["Diseño según normas IRAM", "Detectores en oficinas y archivo", "Protocolo de evacuación"],
    status: "operativo",
    image: "fire-detection",
    summary: "Sistema SDI para la casa de gobierno del ministerio.",
    tags: ["SDI", "Gobierno", "Seguridad"],
  },
  {
    id: 3049,
    title: "Consultoría IT en Modernización del Estado - Gobierno de San Juan",
    client: "Gobierno de San Juan",
    sectorSlug: "gobierno",
    serviceCodes: [106, 104],
    year: 2024, month: 2, location: "San Juan",
    scope: ["Diagnóstico de procesos manuales", "Roadmap de transformación digital", "Acompañamiento en licitaciones"],
    status: "verificado",
    image: "consulting-board",
    summary: "Plan de modernización integral para la administración pública sanjuanina.",
    tags: ["Consultoría IT", "Modernización del Estado", "Gobierno"],
  },
  {
    id: 3050,
    title: "Cableado Estructurado en Sedes Administrativas - Municipalidad de Maipú",
    client: "Municipalidad de Maipú",
    sectorSlug: "gobierno",
    serviceCodes: [101, 108],
    year: 2023, month: 3, location: "Maipú",
    scope: ["Cableado categoría 6A certificado", "Racks organizados por sede", "Documentación completa entregada"],
    status: "verificado",
    image: "network-cabinet",
    summary: "Cableado estructurado para las sedes administrativas del municipio.",
    tags: ["Cableado estructurado", "Redes", "Gobierno"],
  },
  {
    id: 3051,
    title: "Soporte IT 24/7 para Data Center Gubernamental - Gobierno de Mendoza",
    client: "Gobierno de Mendoza",
    sectorSlug: "gobierno",
    serviceCodes: [105, 106],
    year: 2025, month: 1, location: "Mendoza City",
    scope: ["Mesa de ayuda prioritaria para áreas críticas", "Monitoreo 24/7 de infraestructura", "Escalado jerárquico de incidentes"],
    status: "operativo",
    image: "datacenter",
    summary: "Soporte IT de misión crítica para el data center del gobierno provincial.",
    tags: ["Soporte 24/7", "Data Center", "Gobierno"],
  },
  {
    id: 3052,
    title: "Desarrollo de Software de Trámites Online - Municipalidad de Guaymallén",
    client: "Municipalidad de Guaymallén",
    sectorSlug: "gobierno",
    serviceCodes: [104, 106],
    year: 2024, month: 7, location: "Guaymallén",
    scope: ["Portal de trámites online con identidad digital", "Integración con sistema de pagos", "Backoffice para agentes"],
    status: "verificado",
    image: "software-screen",
    summary: "Plataforma web para la gestión digital de trámites municipales.",
    tags: ["Software", "Trámites online", "Gobierno"],
  },
  {
    id: 3053,
    title: "Infraestructura de Red para Hospitales Públicos - Ministerio de Salud Mendoza",
    client: "Ministerio de Salud Mendoza",
    sectorSlug: "gobierno",
    serviceCodes: [101, 105],
    year: 2023, month: 10, location: "Mendoza City",
    scope: ["Red segregada para datos clínicos", "VLAN dedicada para imágenes médicas", "Soporte 24/7 para áreas críticas"],
    status: "verificado",
    image: "hospital-network",
    summary: "Infraestructura de red unificada para la red de hospitales públicos provinciales.",
    tags: ["Redes", "Salud pública", "Gobierno"],
  },
  {
    id: 3054,
    title: "Mantenimiento de Sistemas de Seguridad - Dirección General de Escuelas",
    client: "Dirección General de Escuelas",
    sectorSlug: "gobierno",
    serviceCodes: [102, 105],
    year: 2022, month: 4, location: "Mendoza City",
    scope: ["Mantenimiento preventivo de CCTV", "Actualización de firmware", "Limpieza y calibración de cámaras"],
    status: "mantenimiento",
    image: "cctv-camera",
    summary: "Servicio de mantenimiento para los sistemas de seguridad en escuelas.",
    tags: ["Mantenimiento", "CCTV", "Gobierno"],
  },
  {
    id: 3055,
    title: "Cámaras IP para Centros Vecinales - Municipalidad de Lavalle",
    client: "Municipalidad de Lavalle",
    sectorSlug: "gobierno",
    serviceCodes: [102, 105],
    year: 2024, month: 8, location: "Lavalle",
    scope: ["Cámaras IP en 14 centros vecinales", "Conectividad 4G de respaldo", "Acceso compartido con juntas vecinales"],
    status: "operativo",
    image: "cctv-camera",
    summary: "Red de cámaras IP distribuida en centros vecinales del departamento.",
    tags: ["CCTV", "Centros vecinales", "Gobierno"],
  },
  {
    id: 3056,
    title: "Sistema de Detección de Incendios en Archivo Provincial - Gobierno de Mendoza",
    client: "Gobierno de Mendoza",
    sectorSlug: "gobierno",
    serviceCodes: [107, 105],
    year: 2023, month: 12, location: "Mendoza City",
    scope: ["Detectores aspirantes para archivos documentales", "Sistema de extinción por gas", "Cumplimiento normativo estricto"],
    status: "verificado",
    image: "fire-detection",
    summary: "Sistema SDI de alta sensibilidad para el archivo histórico provincial.",
    tags: ["SDI", "Archivo", "Gobierno"],
  },
  {
    id: 3057,
    title: "Redes de Datos para Sedes Judiciales - Poder Judicial Mendoza",
    client: "Poder Judicial Mendoza",
    sectorSlug: "gobierno",
    serviceCodes: [101, 105],
    year: 2024, month: 5, location: "Mendoza City",
    scope: ["Redes segregadas por fuero", "VPN site-to-site entre tribunales", "Cifrado de expedientes digitales"],
    status: "verificado",
    image: "network-cabinet",
    summary: "Infraestructura de red segura para sedes judiciales provinciales.",
    tags: ["Redes", "Poder Judicial", "Gobierno"],
  },
  {
    id: 3058,
    title: "Consultoría IT en Ciberseguridad - Ministerio de Gobierno",
    client: "Ministerio de Gobierno",
    sectorSlug: "gobierno",
    serviceCodes: [106, 102],
    year: 2025, month: 2, location: "Mendoza City",
    scope: ["Auditoría de ciberseguridad", "Plan de respuesta a incidentes", "Capacitación a personal técnico"],
    status: "operativo",
    image: "consulting-board",
    summary: "Auditoría y plan de mejora de ciberseguridad para el ministerio.",
    tags: ["Consultoría IT", "Ciberseguridad", "Gobierno"],
  },
  {
    id: 3059,
    title: "Implementación de Fibra Óptica - Municipalidad de Luján de Cuyo",
    client: "Municipalidad de Luján de Cuyo",
    sectorSlug: "gobierno",
    serviceCodes: [101, 103],
    year: 2023, month: 6, location: "Luján de Cuyo",
    scope: ["Fibra óptica entre dependencias", "Certificación de enlaces con OTDR", "Empalmes fusionados"],
    status: "verificado",
    image: "fiber-optic",
    summary: "Backbone de fibra óptica que interconecta las dependencias del municipio.",
    tags: ["Fibra óptica", "Redes", "Gobierno"],
  },
  {
    id: 3060,
    title: "Soporte IT para Centros de Salud - Gobierno de San Luis",
    client: "Gobierno de San Luis",
    sectorSlug: "gobierno",
    serviceCodes: [105, 106],
    year: 2024, month: 10, location: "San Luis",
    scope: ["Mesa de ayuda con SLA de 4 horas", "Soporte a centros de salud periféricos", "Mantenimiento de estaciones de trabajo"],
    status: "operativo",
    image: "hospital-network",
    summary: "Servicio de soporte IT para la red de centros de salud provinciales.",
    tags: ["Soporte 24/7", "Salud pública", "Gobierno"],
  },

  // ───────────────────────── INDUSTRIA (15) ─────────────────────────
  {
    id: 3061,
    title: "Mantenimiento Crítico de Sistemas de Detección - Cela SA",
    client: "Cela SA",
    sectorSlug: "industria",
    serviceCodes: [107, 105],
    year: 2024, month: 3, location: "Mendoza City",
    scope: ["Mantenimiento preventivo programado", "Pruebas de detectores y pulsadores", "Protocolo de response 24/7"],
    status: "verificado",
    image: "fire-detection",
    summary: "Plan de mantenimiento crítico para el sistema SDI en planta industrial continua.",
    tags: ["SDI", "Mantenimiento", "Industria"],
  },
  {
    id: 3062,
    title: "Implementación de Redes Industriales - Industria Alimenticia Cuyo",
    client: "Industria Alimenticia Cuyo",
    sectorSlug: "industria",
    serviceCodes: [101, 103],
    year: 2023, month: 7, location: "Mendoza City",
    scope: ["Switches industrializados ruggedizados", "Anillo de fibra con recuperación <50ms", "Protocolos industriales PROFINET"],
    status: "verificado",
    image: "factory-floor",
    summary: "Red industrial tolerante a fallas para planta de producción alimenticia.",
    tags: ["Redes industriales", "Industria 4.0", "Alimenticia"],
  },
  {
    id: 3063,
    title: "Cámaras de CCTV IP para Planta Industrial - Metallurgica Andina",
    client: "Metallurgica Andina",
    sectorSlug: "industria",
    serviceCodes: [102, 105],
    year: 2024, month: 9, location: "Mendoza City",
    scope: ["Cámaras IP certificadas IP67", "Cubiertas resistentes a polvo metálico", "Monitoreo 24/7 de líneas"],
    status: "operativo",
    image: "cctv-camera",
    summary: "Sistema de CCTV IP para control de seguridad y producción en planta metalúrgica.",
    tags: ["CCTV", "Industrial", "Metalurgia"],
  },
  {
    id: 3064,
    title: "Sistema de Detección de Incendios en Naves - Industria Alimenticia Cuyo",
    client: "Industria Alimenticia Cuyo",
    sectorSlug: "industria",
    serviceCodes: [107, 105],
    year: 2022, month: 5, location: "Mendoza City",
    scope: ["Detectores de llama en zonas de proceso", "Sistema de extinción por agua nebulizada", "Cumplimiento FDA y HACCP"],
    status: "verificado",
    image: "fire-detection",
    summary: "Sistema SDI para naves de proceso con cumplimiento de normas alimenticias.",
    tags: ["SDI", "Alimenticia", "Industrial"],
  },
  {
    id: 3065,
    title: "Cableado Estructurado en Línea de Producción - Plásticos del Sur",
    client: "Plásticos del Sur",
    sectorSlug: "industria",
    serviceCodes: [101, 108],
    year: 2023, month: 2, location: "San Rafael",
    scope: ["Cableado categoría 6A certificado", "Tableros eléctricos de uso IT", "Racks sellados para ambiente industrial"],
    status: "operativo",
    image: "network-cabinet",
    summary: "Cableado estructurado para la nueva línea de producción de plásticos.",
    tags: ["Cableado estructurado", "Eléctricos IT", "Plásticos"],
  },
  {
    id: 3066,
    title: "Soporte IT 24/7 para Operaciones Continuas - Cela SA",
    client: "Cela SA",
    sectorSlug: "industria",
    serviceCodes: [105, 106],
    year: 2025, month: 2, location: "Mendoza City",
    scope: ["Mesa de ayuda con SLA de 2 horas", "Técnico onsite rotativo 24/7", "Monitoreo proactivo de infraestructura"],
    status: "operativo",
    image: "server-room",
    summary: "Soporte IT permanente para planta industrial de operación 24/7.",
    tags: ["Soporte 24/7", "Industrial", "Consultoría IT"],
  },
  {
    id: 3067,
    title: "Infraestructura Eléctrica IT en Planta - Química Mendocina",
    client: "Química Mendocina",
    sectorSlug: "industria",
    serviceCodes: [108, 101],
    year: 2024, month: 11, location: "Mendoza City",
    scope: ["Tablero IT con selectividad y antormenta", "UPS para cargas críticas certificadas", "Telemetría de energía en tiempo real"],
    status: "verificado",
    image: "electrical-panel",
    summary: "Infraestructura eléctrica IT certificada para planta química.",
    tags: ["Eléctricos IT", "Química", "Industrial"],
  },
  {
    id: 3068,
    title: "Consultoría IT en Industria 4.0 - Metallurgica Andina",
    client: "Metallurgica Andina",
    sectorSlug: "industria",
    serviceCodes: [106, 104],
    year: 2023, month: 8, location: "Mendoza City",
    scope: ["Diagnóstico de procesos manuales", "Roadmap de digitalización por fases", "Selección de stack tecnológico"],
    status: "verificado",
    image: "consulting-board",
    summary: "Plan de transformación hacia Industria 4.0 para planta metalúrgica.",
    tags: ["Consultoría IT", "Industria 4.0", "Metalurgia"],
  },
  {
    id: 3069,
    title: "Desarrollo de Software de Monitoreo de Planta - Plásticos del Sur",
    client: "Plásticos del Sur",
    sectorSlug: "industria",
    serviceCodes: [104, 106],
    year: 2024, month: 6, location: "San Rafael",
    scope: ["Plataforma SCADA web-based", "Integración con PLCs vía OPC UA", "Dashboard de KPIs en tiempo real"],
    status: "operativo",
    image: "software-screen",
    summary: "Software a medida para el monitoreo y control de la planta plástica.",
    tags: ["Software", "SCADA", "Industrial"],
  },
  {
    id: 3070,
    title: "Mantenimiento de Redes Industriales - Industria Alimenticia Cuyo",
    client: "Industria Alimenticia Cuyo",
    sectorSlug: "industria",
    serviceCodes: [101, 105],
    year: 2022, month: 12, location: "Mendoza City",
    scope: ["Mantenimiento preventivo de switches", "Actualización de firmware industrial", "Parcheos de seguridad programados"],
    status: "mantenimiento",
    image: "factory-floor",
    summary: "Servicio de mantenimiento para la red industrial de la planta alimenticia.",
    tags: ["Mantenimiento", "Redes industriales", "Alimenticia"],
  },
  {
    id: 3071,
    title: "Sistema SDI en Depósitos de Materia Prima - Química Mendocina",
    client: "Química Mendocina",
    sectorSlug: "industria",
    serviceCodes: [107, 105],
    year: 2023, month: 4, location: "Mendoza City",
    scope: ["Detectores de gas y humo combinados", "Sistema de extinción por gas limpio", "Protocolo ATEX para zonas peligrosas"],
    status: "verificado",
    image: "fire-detection",
    summary: "Sistema SDI para depósitos de materia prima química con clasificación ATEX.",
    tags: ["SDI", "Química", "ATEX"],
  },
  {
    id: 3072,
    title: "Cámaras IP para Control de Calidad - Cela SA",
    client: "Cela SA",
    sectorSlug: "industria",
    serviceCodes: [102, 105],
    year: 2024, month: 7, location: "Mendoza City",
    scope: ["Cámaras IP en línea de control", "Analítica de video para conteo de piezas", "Alertas de defectos en tiempo real"],
    status: "operativo",
    image: "cctv-camera",
    summary: "Sistema de visión artificial para control de calidad en línea de producción.",
    tags: ["CCTV", "Analítica de video", "Industrial"],
  },
  {
    id: 3073,
    title: "Instalación Eléctrica para Tableros IT - Metallurgica Andina",
    client: "Metallurgica Andina",
    sectorSlug: "industria",
    serviceCodes: [108, 101],
    year: 2022, month: 9, location: "Mendoza City",
    scope: ["Tableros IT para sala de servidores", "UPS con autonomía de 45 minutos", "Sistema de tierra dedicada"],
    status: "operativo",
    image: "electrical-panel",
    summary: "Instalación eléctrica para la sala de servidores de la planta metalúrgica.",
    tags: ["Eléctricos IT", "Metalurgia", "Industrial"],
  },
  {
    id: 3074,
    title: "Detección de Incendios en Sala de Calderas - Plásticos del Sur",
    client: "Plásticos del Sur",
    sectorSlug: "industria",
    serviceCodes: [107, 105],
    year: 2025, month: 1, location: "San Rafael",
    scope: ["Detectores de llama UV/IR", "Sistema de extinción por espuma", "Monitoreo 24/7 con response garantizado"],
    status: "operativo",
    image: "fire-detection",
    summary: "Sistema SDI para la sala de calderas de la planta plástica.",
    tags: ["SDI", "Calderas", "Industrial"],
  },
  {
    id: 3075,
    title: "Redes de Datos para Planta Automatizada - Industria Alimenticia Cuyo",
    client: "Industria Alimenticia Cuyo",
    sectorSlug: "industria",
    serviceCodes: [101, 103],
    year: 2023, month: 11, location: "Mendoza City",
    scope: ["Red industrial para robótica", "Integración con MES y ERP", "Wi-Fi 6 para AGVs"],
    status: "verificado",
    image: "factory-floor",
    summary: "Infraestructura de red para la nueva planta robotizada de alta producción.",
    tags: ["Redes industriales", "Robótica", "Alimenticia"],
  },

  // ───────────────────────── MINERÍA (10) ─────────────────────────
  {
    id: 3076,
    title: "Implementación de Redes de Datos y Fibra Óptica - Minera Frontera",
    client: "Minera Frontera",
    sectorSlug: "mineria",
    serviceCodes: [101, 103],
    year: 2024, month: 4, location: "Neuquén",
    scope: ["Tendido de 22 km de fibra óptica monomodo", "Conectividad entre faena y campamento", "Certificación de enlaces con OTDR"],
    status: "verificado",
    image: "fiber-optic",
    summary: "Backbone de fibra óptica para una faena minera de gran extensión.",
    tags: ["Fibra óptica", "Redes", "Minería"],
  },
  {
    id: 3077,
    title: "Cámaras de CCTV IP para Faena Minera - Minera Andina del Sur",
    client: "Minera Andina del Sur",
    sectorSlug: "mineria",
    serviceCodes: [102, 105],
    year: 2023, month: 9, location: "San Juan",
    scope: ["Cámaras IP certificadas IP67", "Cobertura de polvorines y accesos", "Transmisión por radioenlace"],
    status: "verificado",
    image: "cctv-perimeter",
    summary: "Sistema de CCTV IP para vigilancia perimetral de faena minera.",
    tags: ["CCTV", "Minería", "Perímetro"],
  },
  {
    id: 3078,
    title: "Sistema de Detección en Polvorines - Minera Frontera",
    client: "Minera Frontera",
    sectorSlug: "mineria",
    serviceCodes: [107, 105],
    year: 2024, month: 11, location: "Neuquén",
    scope: ["Detectores de llama UV/IR", "Sistema de extinción automático", "Protocolo ATEX estricto"],
    status: "verificado",
    image: "fire-detection",
    summary: "Sistema SDI certificado ATEX para polvorines de explosivos.",
    tags: ["SDI", "Polvorines", "ATEX"],
  },
  {
    id: 3079,
    title: "Telecomunicaciones para Campamento Minero - Minera Cuyo",
    client: "Minera Cuyo",
    sectorSlug: "mineria",
    serviceCodes: [103, 101],
    year: 2023, month: 6, location: "San Juan",
    scope: ["Enlaces de microondas licenciados", "Conectividad VSAT de respaldo", "Telefonía IP para campamento"],
    status: "operativo",
    image: "telecom-tower",
    summary: "Solución integral de telecomunicaciones para campamento minero remoto.",
    tags: ["Telecomunicaciones", "Campamento", "Minería"],
  },
  {
    id: 3080,
    title: "Mantenimiento Crítico de Redes - Minera Andina del Sur",
    client: "Minera Andina del Sur",
    sectorSlug: "mineria",
    serviceCodes: [101, 105],
    year: 2025, month: 1, location: "San Juan",
    scope: ["Mantenimiento preventivo de enlaces", "Pruebas periódicas de OTDR", "Response 24/7 con técnico onsite"],
    status: "mantenimiento",
    image: "server-room",
    summary: "Servicio de mantenimiento para la infraestructura de red de la faena.",
    tags: ["Mantenimiento", "Redes", "Minería"],
  },
  {
    id: 3081,
    title: "Soporte IT 24/7 para Faena Remota - Minera Frontera",
    client: "Minera Frontera",
    sectorSlug: "mineria",
    serviceCodes: [105, 106],
    year: 2024, month: 8, location: "Neuquén",
    scope: ["Mesa de ayuda con SLA de 2 horas", "Técnico rotativo en campamento", "Monitoreo 24/7 de infraestructura"],
    status: "operativo",
    image: "mining-site",
    summary: "Servicio intensivo de soporte IT para faena minera de acceso remoto.",
    tags: ["Soporte 24/7", "Consultoría IT", "Minería"],
  },
  {
    id: 3082,
    title: "Consultoría IT en Conectividad Minera - Minera Cuyo",
    client: "Minera Cuyo",
    sectorSlug: "mineria",
    serviceCodes: [106, 103],
    year: 2023, month: 10, location: "San Juan",
    scope: ["Auditoría de conectividad existente", "Plan de mejora por fases", "Definición de arquitectura de red"],
    status: "verificado",
    image: "consulting-board",
    summary: "Consultoría para optimizar la conectividad de la faena minera.",
    tags: ["Consultoría IT", "Conectividad", "Minería"],
  },
  {
    id: 3083,
    title: "Cableado Estructurado en Casa de Fuerza - Minera Patagonia",
    client: "Minera Patagonia",
    sectorSlug: "mineria",
    serviceCodes: [101, 108],
    year: 2022, month: 7, location: "Neuquén",
    scope: ["Cableado categoría 6A certificado", "Tableros IT para casa de fuerza", "Racks sellados para ambiente hostil"],
    status: "operativo",
    image: "network-cabinet",
    summary: "Cableado estructurado y tableros IT para la casa de fuerza de la mina.",
    tags: ["Cableado estructurado", "Eléctricos IT", "Minería"],
  },
  {
    id: 3084,
    title: "Sistema SDI en Túneles de Acceso - Minera Frontera",
    client: "Minera Frontera",
    sectorSlug: "mineria",
    serviceCodes: [107, 105],
    year: 2024, month: 5, location: "Neuquén",
    scope: ["Detectores lineales de humo para túneles", "Alarmas sonoras y luminosas", "Protocolo de evacuación subterránea"],
    status: "verificado",
    image: "fire-detection",
    summary: "Sistema SDI para túneles de acceso a la mina con protocolos de evacuación.",
    tags: ["SDI", "Túneles", "Minería"],
  },
  {
    id: 3085,
    title: "Infraestructura Eléctrica IT en Subestación - Minera Andina del Sur",
    client: "Minera Andina del Sur",
    sectorSlug: "mineria",
    serviceCodes: [108, 101],
    year: 2023, month: 3, location: "San Juan",
    scope: ["Tablero IT para subestación eléctrica", "UPS con autonomía extendida", "Telemetría de energía en tiempo real"],
    status: "operativo",
    image: "electrical-panel",
    summary: "Infraestructura eléctrica IT para la subestación de la faena minera.",
    tags: ["Eléctricos IT", "Subestación", "Minería"],
  },

  // ───────────────────────── SALUD (16) ─────────────────────────
  {
    id: 3086,
    title: "Infraestructura Hospitalaria: Rack y patch panel - Hospital A Italo Perrupato",
    client: "Hospital A Italo Perrupato",
    sectorSlug: "salud",
    serviceCodes: [101, 105],
    year: 2024, month: 3, location: "San Martín",
    scope: ["Rack y patch panel certificados", "Red segregada para datos clínicos", "Soporte 24/7 para áreas críticas"],
    status: "verificado",
    image: "hospital-rack",
    summary: "Infraestructura de red hospitalaria para el sistema de historia clínica digital.",
    tags: ["Redes", "Hospitalario", "Salud"],
  },
  {
    id: 3087,
    title: "Implementación de Redes de Datos y Fibra Óptica - FUESMEN",
    client: "FUESMEN",
    sectorSlug: "salud",
    serviceCodes: [101, 103],
    year: 2023, month: 5, location: "Mendoza City",
    scope: ["Fibra óptica entre pabellones", "Certificación de enlaces con OTDR", "VLAN dedicada para imágenes médicas"],
    status: "verificado",
    image: "fiber-optic",
    summary: "Backbone de fibra óptica que interconecta los pabellones del hospital.",
    tags: ["Fibra óptica", "Redes", "Salud"],
  },
  {
    id: 3088,
    title: "Cámaras de CCTV IP para FUNDACION COPROSAMEN",
    client: "Fundación COPROSAMEN",
    sectorSlug: "salud",
    serviceCodes: [102, 105],
    year: 2024, month: 9, location: "Mendoza City",
    scope: ["Cámaras IP en áreas comunes y críticas", "Centro de monitoreo 24/7", "Control de accesos por zona"],
    status: "operativo",
    image: "cctv-camera",
    summary: "Sistema de CCTV IP para la seguridad de pacientes y personal de la fundación.",
    tags: ["CCTV", "Salud", "Seguridad"],
  },
  {
    id: 3089,
    title: "Soporte IT para Hospital Central Mendoza",
    client: "Hospital Central Mendoza",
    sectorSlug: "salud",
    serviceCodes: [105, 106],
    year: 2025, month: 2, location: "Mendoza City",
    scope: ["Mesa de ayuda 24/7 con SLA prioritario", "Técnico onsite rotativo", "Mantenimiento preventivo programado"],
    status: "operativo",
    image: "hospital-network",
    summary: "Soporte IT permanente para el hospital más grande de la provincia.",
    tags: ["Soporte 24/7", "Hospitalario", "Salud"],
  },
  {
    id: 3090,
    title: "Sistema de Detección en Áreas Críticas - Hospital Perrupato",
    client: "Hospital Perrupato",
    sectorSlug: "salud",
    serviceCodes: [107, 105],
    year: 2024, month: 7, location: "San Martín",
    scope: ["Detectores en terapia intensiva y quirófanos", "Sistema de extinción por gas limpio", "Protocolo de evacuación"],
    status: "verificado",
    image: "fire-detection",
    summary: "Sistema SDI para áreas críticas hospitalarias con extinción por gas.",
    tags: ["SDI", "Hospitalario", "Crítico"],
  },
  {
    id: 3091,
    title: "Cableado Estructurado en Sector de Terapia Intensiva - Hospital Central Mendoza",
    client: "Hospital Central Mendoza",
    sectorSlug: "salud",
    serviceCodes: [101, 108],
    year: 2023, month: 8, location: "Mendoza City",
    scope: ["Cableado categoría 6A certificado", "Tableros IT con UPS de respaldo", "Redundancia total para terapia intensiva"],
    status: "verificado",
    image: "network-cabinet",
    summary: "Cableado estructurado certificado para el sector de terapia intensiva.",
    tags: ["Cableado estructurado", "Terapia intensiva", "Salud"],
  },
  {
    id: 3092,
    title: "Mantenimiento Crítico de Redes Hospitalarias - FUESMEN",
    client: "FUESMEN",
    sectorSlug: "salud",
    serviceCodes: [101, 105],
    year: 2024, month: 11, location: "Mendoza City",
    scope: ["Mantenimiento preventivo de switches", "Parcheos de seguridad programados", "Monitoreo 24/7 de infraestructura"],
    status: "mantenimiento",
    image: "server-room",
    summary: "Servicio de mantenimiento crítico para la red hospitalaria.",
    tags: ["Mantenimiento", "Redes", "Salud"],
  },
  {
    id: 3093,
    title: "Desarrollo de Software de Gestión de Pacientes - COPROSAMEN",
    client: "Fundación COPROSAMEN",
    sectorSlug: "salud",
    serviceCodes: [104, 106],
    year: 2023, month: 4, location: "Mendoza City",
    scope: ["Aplicación web con roles y permisos", "Integración con sistemas de imágenes", "Cumplimiento de privacidad de datos"],
    status: "verificado",
    image: "software-screen",
    summary: "Sistema a medida para la gestión integral de pacientes y turnos.",
    tags: ["Software", "Gestión de pacientes", "Salud"],
  },
  {
    id: 3094,
    title: "Consultoría IT en Historia Clínica Digital - Hospital Perrupato",
    client: "Hospital Perrupato",
    sectorSlug: "salud",
    serviceCodes: [106, 104],
    year: 2024, month: 6, location: "San Martín",
    scope: ["Diagnóstico de procesos clínicos", "Roadmap de digitalización", "Selección de estándares (HL7, FHIR)"],
    status: "verificado",
    image: "consulting-board",
    summary: "Plan para la implementación de la historia clínica digital del hospital.",
    tags: ["Consultoría IT", "Historia clínica", "Salud"],
  },
  {
    id: 3095,
    title: "Infraestructura IT para Centro de Diagnóstico - FUESMEN",
    client: "FUESMEN",
    sectorSlug: "salud",
    serviceCodes: [101, 105],
    year: 2023, month: 12, location: "Mendoza City",
    scope: ["Red de alta disponibilidad para imágenes", "Almacenamiento redundante PACS", "Soporte 24/7 para equipos médicos"],
    status: "verificado",
    image: "hospital-network",
    summary: "Infraestructura IT completa para el nuevo centro de diagnóstico por imágenes.",
    tags: ["Redes", "PACS", "Salud"],
  },
  {
    id: 3096,
    title: "Cámaras IP para Control de Accesos - Hospital Central Mendoza",
    client: "Hospital Central Mendoza",
    sectorSlug: "salud",
    serviceCodes: [102, 105],
    year: 2024, month: 2, location: "Mendoza City",
    scope: ["Cámaras IP en ingresos y áreas restringidas", "Control de accesos con tarjetas MIFARE", "Auditoría completa de accesos"],
    status: "operativo",
    image: "cctv-camera",
    summary: "Sistema de CCTV y control de accesos para áreas restringidas del hospital.",
    tags: ["CCTV", "Control de accesos", "Salud"],
  },
  {
    id: 3097,
    title: "Sistema SDI en Sala de Máquinas - Hospital Perrupato",
    client: "Hospital Perrupato",
    sectorSlug: "salud",
    serviceCodes: [107, 105],
    year: 2022, month: 10, location: "San Martín",
    scope: ["Detectores de humo y temperatura", "Sistema de extinción por gas", "Mantenimiento trimestral"],
    status: "verificado",
    image: "fire-detection",
    summary: "Sistema SDI para la sala de máquinas del hospital.",
    tags: ["SDI", "Sala de máquinas", "Salud"],
  },
  {
    id: 3098,
    title: "Redes de Datos para Imágenes Médicas - FUESMEN",
    client: "FUESMEN",
    sectorSlug: "salud",
    serviceCodes: [101, 103],
    year: 2025, month: 1, location: "Mendoza City",
    scope: ["Red de alta velocidad para imágenes DICOM", "VLAN aislada para equipos médicos", "QoS para tráfico de imágenes"],
    status: "operativo",
    image: "hospital-network",
    summary: "Red de datos optimizada para el transporte de imágenes médicas pesadas.",
    tags: ["Redes", "DICOM", "Salud"],
  },
  {
    id: 3099,
    title: "Soporte IT 24/7 para Guardia Hospitalaria - Hospital Central Mendoza",
    client: "Hospital Central Mendoza",
    sectorSlug: "salud",
    serviceCodes: [105, 106],
    year: 2024, month: 5, location: "Mendoza City",
    scope: ["Mesa de ayuda prioritaria para guardia", "Técnico onsite 24/7", "Response garantizado en 1 hora"],
    status: "operativo",
    image: "server-room",
    summary: "Servicio de soporte IT permanente para la guardia hospitalaria.",
    tags: ["Soporte 24/7", "Guardia", "Salud"],
  },
  {
    id: 3100,
    title: "Instalación Eléctrica para Data Center Hospitalario - COPROSAMEN",
    client: "Fundación COPROSAMEN",
    sectorSlug: "salud",
    serviceCodes: [108, 101],
    year: 2023, month: 7, location: "Mendoza City",
    scope: ["Tablero IT con selectividad", "UPS con autonomía de 60 minutos", "Sistema de tierra dedicada"],
    status: "verificado",
    image: "electrical-panel",
    summary: "Instalación eléctrica crítica para el data center hospitalario.",
    tags: ["Eléctricos IT", "Data Center", "Salud"],
  },
  {
    id: 3101,
    title: "Detección de Incendios en Áreas Hospitalarias - Hospital Perrupato",
    client: "Hospital Perrupato",
    sectorSlug: "salud",
    serviceCodes: [107, 105],
    year: 2024, month: 8, location: "San Martín",
    scope: ["Detectores en habitaciones y pasillos", "Sirenas y balizas multisede", "Integración con sistema de evacuación"],
    status: "operativo",
    image: "fire-detection",
    summary: "Sistema SDI para áreas hospitalarias con protocolo de evacuación.",
    tags: ["SDI", "Hospitalario", "Salud"],
  },

  // ───────────────────────── SEGURIDAD ELECTRÓNICA (11) ─────────────────────────
  {
    id: 3102,
    title: "Centro de Monitoreo de CCTV 24/7 - Consorcio Edificios Centro",
    client: "Consorcio Edificios Centro",
    sectorSlug: "seguridad-electronica",
    serviceCodes: [102, 105],
    year: 2024, month: 3, location: "Mendoza City",
    scope: ["Diseño de centro de operaciones 24/7", "Integración PSIM multisede", "Operadores capacitados"],
    status: "verificado",
    image: "control-room",
    summary: "Centro de operaciones unificado para el monitoreo de varios edificios corporativos.",
    tags: ["Centro de monitoreo", "CCTV", "Seguridad"],
  },
  {
    id: 3103,
    title: "Sistema de Control de Accesos Biometría - Banco Regional Cuyo",
    client: "Banco Regional Cuyo",
    sectorSlug: "seguridad-electronica",
    serviceCodes: [102, 104],
    year: 2023, month: 6, location: "Mendoza City",
    scope: ["Lectores biométricos con anti-spoofing", "Integración con sistema de RRHH", "Auditoría de accesos completa"],
    status: "verificado",
    image: "biometric-access",
    summary: "Sistema de control de accesos biométrico para áreas restringidas del banco.",
    tags: ["Biometría", "Control de accesos", "Banca"],
  },
  {
    id: 3104,
    title: "Cámaras IP de Alta Resolución para Banco - Banco Regional Cuyo",
    client: "Banco Regional Cuyo",
    sectorSlug: "seguridad-electronica",
    serviceCodes: [102, 105],
    year: 2024, month: 9, location: "Mendoza City",
    scope: ["Cámaras IP 4K en caja y acceso", "Grabación con retención de 90 días", "Cifrado de video extremo a extremo"],
    status: "verificado",
    image: "cctv-camera",
    summary: "Sistema de CCTV IP de alta resolución para sucursales bancarias.",
    tags: ["CCTV", "Banca", "Seguridad"],
  },
  {
    id: 3105,
    title: "Mantenimiento de Sistemas de Seguridad - Shopping Center Mendoza",
    client: "Shopping Center Mendoza",
    sectorSlug: "seguridad-electronica",
    serviceCodes: [102, 105],
    year: 2023, month: 11, location: "Mendoza City",
    scope: ["Mantenimiento preventivo de CCTV", "Calibración de control de accesos", "Actualización de firmware"],
    status: "mantenimiento",
    image: "cctv-camera",
    summary: "Servicio de mantenimiento para los sistemas de seguridad del shopping.",
    tags: ["Mantenimiento", "CCTV", "Retail"],
  },
  {
    id: 3106,
    title: "Detección de Intrusión en Perímetro - Logística Andina",
    client: "Logística Andina",
    sectorSlug: "seguridad-electronica",
    serviceCodes: [102, 107],
    year: 2024, month: 7, location: "Mendoza City",
    scope: ["Sensores sísmicos en perímetro", "Cámaras IP con analítica de video", "Integración con centro de monitoreo"],
    status: "verificado",
    image: "cctv-perimeter",
    summary: "Sistema de detección de intrusión perimetral para el centro logístico.",
    tags: ["Detección de intrusión", "Perímetro", "Logística"],
  },
  {
    id: 3107,
    title: "Consultoría IT en Ciberseguridad Física - Cámara de Comercio Mendoza",
    client: "Cámara de Comercio Mendoza",
    sectorSlug: "seguridad-electronica",
    serviceCodes: [106, 102],
    year: 2025, month: 2, location: "Mendoza City",
    scope: ["Auditoría de ciberseguridad física", "Plan de respuesta a incidentes", "Capacitación a personal técnico"],
    status: "operativo",
    image: "consulting-board",
    summary: "Consultoría integral de ciberseguridad física para socios de la cámara.",
    tags: ["Consultoría IT", "Ciberseguridad", "Seguridad"],
  },
  {
    id: 3108,
    title: "Sistema SDI en Edificios Corporativos - Consorcio Edificios Centro",
    client: "Consorcio Edificios Centro",
    sectorSlug: "seguridad-electronica",
    serviceCodes: [107, 105],
    year: 2023, month: 4, location: "Mendoza City",
    scope: ["Detectores en áreas comunes y técnicos", "Sirenas y balizas multisede", "Protocolo de evacuación"],
    status: "verificado",
    image: "fire-detection",
    summary: "Sistema SDI multisede para edificios corporativos del centro de la ciudad.",
    tags: ["SDI", "Corporativo", "Seguridad"],
  },
  {
    id: 3109,
    title: "Cámaras de CCTV para Casino - Entretenimiento Cuyo SA",
    client: "Entretenimiento Cuyo SA",
    sectorSlug: "seguridad-electronica",
    serviceCodes: [102, 105],
    year: 2024, month: 8, location: "Mendoza City",
    scope: ["Cámaras IP sobre cada mesa de juego", "Grabación con retención extendida", "Integración con sistema de tragamonedas"],
    status: "verificado",
    image: "cctv-camera",
    summary: "Sistema de CCTV IP certificado para sala de juegos del casino.",
    tags: ["CCTV", "Casino", "Seguridad"],
  },
  {
    id: 3110,
    title: "Control de Accesos Vehiculares - Estacionamiento Central",
    client: "Estacionamiento Central",
    sectorSlug: "seguridad-electronica",
    serviceCodes: [102, 104],
    year: 2023, month: 9, location: "Mendoza City",
    scope: ["Barreras vehiculares con LPR", "Software de gestión de estacionamiento", "Integración con sistema de pagos"],
    status: "operativo",
    image: "barrier-access",
    summary: "Sistema de control de accesos vehiculares con reconocimiento de patentes.",
    tags: ["Control de accesos", "LPR", "Estacionamiento"],
  },
  {
    id: 3111,
    title: "Soporte 24/7 para Centro de Monitoreo - Consorcio Edificios Centro",
    client: "Consorcio Edificios Centro",
    sectorSlug: "seguridad-electronica",
    serviceCodes: [105, 106],
    year: 2025, month: 3, location: "Mendoza City",
    scope: ["Soporte a operadores 24/7", "Mantenimiento preventivo programado", "Escalado jerárquico de incidentes"],
    status: "operativo",
    image: "server-room",
    summary: "Servicio de soporte IT para el centro de monitoreo de seguridad.",
    tags: ["Soporte 24/7", "Centro de monitoreo", "Seguridad"],
  },
  {
    id: 3112,
    title: "Infraestructura de Seguridad para Casino - Entretenimiento Cuyo SA",
    client: "Entretenimiento Cuyo SA",
    sectorSlug: "seguridad-electronica",
    serviceCodes: [102, 108],
    year: 2024, month: 12, location: "Mendoza City",
    scope: ["Infraestructura eléctrica para CCTV", "UPS para sistemas de seguridad", "Tableros IT dedicados"],
    status: "verificado",
    image: "control-room",
    summary: "Infraestructura eléctrica y de red para los sistemas de seguridad del casino.",
    tags: ["Eléctricos IT", "Casino", "Seguridad"],
  },

  // ───────────────────────── SOFTWARE (8) ─────────────────────────
  {
    id: 3113,
    title: "Desarrollo de Software a Medida para ERP - Distribuidora Cuyo",
    client: "Distribuidora Cuyo",
    sectorSlug: "software",
    serviceCodes: [104, 106],
    year: 2024, month: 4, location: "Mendoza City",
    scope: ["Levantamiento de procesos de negocio", "Desarrollo ágil con sprints quincenales", "Integración con sistemas contables"],
    status: "verificado",
    image: "software-screen",
    summary: "ERP a medida para la gestión integral de la distribuidora regional.",
    tags: ["ERP", "Software", "Distribución"],
  },
  {
    id: 3114,
    title: "Implementación de Plataforma E-commerce - Tienda Andina",
    client: "Tienda Andina",
    sectorSlug: "software",
    serviceCodes: [104, 106],
    year: 2023, month: 8, location: "Mendoza City",
    scope: ["Arquitectura headless con Next.js", "Integración con pasarelas de pago", "Pipelines CI/CD automatizados"],
    status: "verificado",
    image: "software-screen",
    summary: "Plataforma e-commerce headless con cobertura multi-país.",
    tags: ["E-commerce", "Headless", "Next.js"],
  },
  {
    id: 3115,
    title: "Mantenimiento de Aplicaciones Web - Logística del Plata",
    client: "Logística del Plata",
    sectorSlug: "software",
    serviceCodes: [104, 105],
    year: 2024, month: 11, location: "Mendoza City",
    scope: ["Mantenimiento correctivo y evolutivo", "Monitoreo de performance APM", "Parcheos de seguridad programados"],
    status: "operativo",
    image: "software-screen",
    summary: "Servicio de mantenimiento evolutivo para el portfolio de aplicaciones web.",
    tags: ["Mantenimiento", "Aplicaciones web", "Logística"],
  },
  {
    id: 3116,
    title: "Consultoría IT en Arquitectura de Software - Fintech Mendoza",
    client: "Fintech Mendoza",
    sectorSlug: "software",
    serviceCodes: [106, 104],
    year: 2025, month: 1, location: "Mendoza City",
    scope: ["Diagnóstico de arquitectura existente", "Roadmap de modernización cloud-native", "Definición de patrones de microservicios"],
    status: "verificado",
    image: "consulting-board",
    summary: "Consultoría para la modernización cloud-native de la plataforma fintech.",
    tags: ["Consultoría IT", "Cloud-native", "Fintech"],
  },
  {
    id: 3117,
    title: "Desarrollo de API para Integración de Sistemas - Distribuidora Cuyo",
    client: "Distribuidora Cuyo",
    sectorSlug: "software",
    serviceCodes: [104, 106],
    year: 2023, month: 6, location: "Mendoza City",
    scope: ["API REST y GraphQL con OAuth2", "Documentación OpenAPI completa", "Gateway de APIs con rate limiting"],
    status: "verificado",
    image: "software-screen",
    summary: "Plataforma de APIs para integrar el ERP con sistemas de terceros.",
    tags: ["API", "GraphQL", "Integración"],
  },
  {
    id: 3118,
    title: "Soporte de Infraestructura Cloud - Fintech Mendoza",
    client: "Fintech Mendoza",
    sectorSlug: "software",
    serviceCodes: [105, 104],
    year: 2024, month: 9, location: "Mendoza City",
    scope: ["Mesa de ayuda con SLA prioritario", "Monitoreo 24/7 de infraestructura cloud", "Gestión de costos y escalado automático"],
    status: "operativo",
    image: "server-room",
    summary: "Servicio de soporte para la infraestructura cloud de la fintech.",
    tags: ["Soporte 24/7", "Cloud", "Fintech"],
  },
  {
    id: 3119,
    title: "Desarrollo de Software para Gestión Logística - Logística del Plata",
    client: "Logística del Plata",
    sectorSlug: "software",
    serviceCodes: [104, 106],
    year: 2023, month: 10, location: "Mendoza City",
    scope: ["Aplicación web con roles y permisos", "Integración con GPS y telemetría", "Dashboard de operaciones en tiempo real"],
    status: "verificado",
    image: "software-screen",
    summary: "Plataforma de gestión logística con tracking en tiempo real de la flota.",
    tags: ["Software", "Logística", "Telemetría"],
  },
  {
    id: 3120,
    title: "Implementación de CI/CD y DevOps - Fintech Mendoza",
    client: "Fintech Mendoza",
    sectorSlug: "software",
    serviceCodes: [104, 106],
    year: 2024, month: 12, location: "Mendoza City",
    scope: ["Pipelines con contenedores", "Observabilidad con métricas y trazas", "Rollback automático y blue-green deploys"],
    status: "verificado",
    image: "software-screen",
    summary: "Implementación de pipelines CI/CD y prácticas DevOps para la fintech.",
    tags: ["DevOps", "CI/CD", "Fintech"],
  },
];

export const ANTECEDENTES: Antecedente[] = SEEDS.map((seed) => ({
  ...seed,
  slug: `${seed.id}-${slugify(seed.title)}`,
}));

// ───────────────────────── HELPERS ─────────────────────────

/** Antecedentes por sector (slug). */
export function getAntecedentesBySector(slug: SectorSlug): Antecedente[] {
  return ANTECEDENTES.filter((a) => a.sectorSlug === slug);
}

/** Antecedentes por código de servicio (101-108). */
export function getAntecedentesByService(code: ServiceCode | number): Antecedente[] {
  return ANTECEDENTES.filter((a) => a.serviceCodes.includes(code as ServiceCode));
}

/** Antecedentes por año. */
export function getAntecedentesByYear(year: number): Antecedente[] {
  return ANTECEDENTES.filter((a) => a.year === year);
}

/** Antecedentes por estado. */
export function getAntecedentesByStatus(status: AntecedenteStatus): Antecedente[] {
  return ANTECEDENTES.filter((a) => a.status === status);
}

/** Búsqueda libre por texto (título, cliente, summary, tags). Case-insensitive, sin acentos. */
export function searchAntecedentes(query: string): Antecedente[] {
  const normalize = (s: string) =>
    s
      .toLowerCase()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "");
  const q = normalize(query.trim());
  if (!q) return ANTECEDENTES;
  return ANTECEDENTES.filter((a) =>
    [a.title, a.client, a.summary, a.location, a.tags.join(" "), a.scope.join(" ")]
      .map(normalize)
      .some((field) => field.includes(q)),
  );
}

/** Antecedente por ID. */
export function getAntecedenteById(id: number): Antecedente | undefined {
  return ANTECEDENTES.find((a) => a.id === id);
}

/** Antecedente por slug. */
export function getAntecedenteBySlug(slug: string): Antecedente | undefined {
  return ANTECEDENTES.find((a) => a.slug === slug);
}

/** Conteo por sector (utilidad para stats de UI). */
export function countAntecedentesBySector(): Record<SectorSlug, number> {
  return ANTECEDENTES.reduce(
    (acc, a) => {
      acc[a.sectorSlug] = (acc[a.sectorSlug] ?? 0) + 1;
      return acc;
    },
    {} as Record<SectorSlug, number>,
  );
}

/** Distribución por año. */
export function countAntecedentesByYear(): Record<number, number> {
  return ANTECEDENTES.reduce(
    (acc, a) => {
      acc[a.year] = (acc[a.year] ?? 0) + 1;
      return acc;
    },
    {} as Record<number, number>,
  );
}

export default ANTECEDENTES;
