import {build} from 'esbuild';
import fs from 'node:fs/promises';
import path from 'node:path';
const requested=process.env.UM_BASE_PATH||'/';
if(!/^\/(?:[a-zA-Z0-9_-]+\/)*$/.test(requested))throw Error('UM_BASE_PATH debe ser / o una subruta absoluta con barra final, sin puntos, consulta ni fragmento.');
const base=requested;
const storage=process.env.UM_STORAGE_MODE||'session';
if(!['session','local'].includes(storage))throw Error('UM_STORAGE_MODE debe ser session o local');
const returnUrl=process.env.UM_RETURN_URL||'/software/gestion-de-comunidades-profesionales';
if(!/^\/(?!\/)[a-zA-Z0-9_/-]*$/.test(returnUrl)&&!/^https:\/\/(www\.)?ultimamilla\.com\.ar(?:\/[a-zA-Z0-9_/-]*)?$/.test(returnUrl))throw Error('UM_RETURN_URL debe apuntar a la web de Última Milla');
const enableSW=process.env.UM_ENABLE_SW==='true';
if(enableSW&&base==='/')throw Error('Service worker opcional sólo permitido bajo una subruta, nunca en la raíz del sitio.');
await fs.rm('dist',{recursive:true,force:true});
await fs.cp('static','dist',{recursive:true});
await build({entryPoints:['src/app.jsx'],bundle:true,outfile:'dist/app.js',minify:true,format:'esm',target:'es2022',jsx:'automatic',jsxImportSource:'react',tsconfigRaw:{compilerOptions:{jsx:'react-jsx',jsxImportSource:'react'}},define:{__APP_BASE__:JSON.stringify(base),__ENABLE_SW__:JSON.stringify(enableSW),__STORAGE_MODE__:JSON.stringify(storage),__RETURN_URL__:JSON.stringify(returnUrl)}});
await build({entryPoints:['src/import-worker.mjs'],bundle:true,outfile:'dist/import-worker.js',minify:true,format:'iife',target:'es2022'});
// Match the reviewed browser worker bundle. The source artifact has no strict
// directive; esbuild can prepend one when nested under the site's tsconfig.
const worker=await fs.readFile('dist/import-worker.js','utf8');
await fs.writeFile('dist/import-worker.js',worker.replace(/^"use strict";/,''));
await fs.copyFile('src/style.css','dist/style.css');
await fs.copyFile('node_modules/pdfjs-dist/build/pdf.worker.min.mjs','dist/pdf.worker.min.mjs');
let html=await fs.readFile('static/index.html','utf8');
html=html.replaceAll('href="./',`href="${base}`).replaceAll('src="./',`src="${base}`);
await fs.writeFile('dist/index.html',html);
const manifest=JSON.parse(await fs.readFile('static/manifest.webmanifest','utf8'));
manifest.id=base;manifest.start_url=base;manifest.scope=base;manifest.background_color='#f4f6f4';manifest.icons=manifest.icons.map(i=>({...i,src:base+path.basename(i.src),purpose:'any'}));
await fs.writeFile('dist/manifest.webmanifest',JSON.stringify(manifest));
if(!enableSW)await fs.rm('dist/sw.js');
await fs.writeFile('dist/build-info.json',JSON.stringify({version:'3.1-portable',base,storage,serviceWorker:enableSW,backend:false},null,2));
console.log(`Build portable completo. Base ${base}; datos ${storage}; SW ${enableSW?'sólo subruta':'desactivado'}`);
