server {
    listen 443 ssl http2;
    server_name emergency.ultimamilla.com.ar;

    ssl_certificate /etc/letsencrypt/live/www.ultimamilla.com.ar/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/www.ultimamilla.com.ar/privkey.pem;

    location / {
        root /usr/share/nginx/html/emergency;
        try_files $uri $uri/ /index.html;
    }
} 