#!/bin/bash
# Script to populate Productos JSON for all services

docker exec umbot-postgres-prod psql -U directus -d directus << 'ENDOFSQL'

-- Service 101: Infraestructura de Redes y Cableado (8 productos)
UPDATE "Servicios" SET "Productos" = '[
  {"nombre":"Fibra Óptica de Alta Capacidad","descripcion":"Olvídese de los cuellos de botella. Con nuestra instalación certificada de fibra óptica, sus datos viajan a la velocidad de la luz.","servicio_asociado":"🔧 Instalamos enlaces de fibra óptica monomodo y multimodo con fusiones certificadas, mediciones OTDR y garantía de 25 años.","imagen":"/images/services/productos/infraestructura/1.1.png","caracteristicas":["Velocidades de hasta 100 Gbps","Inmune a interferencias electromagnéticas","Distancias de hasta 80 km sin repetidores"]},
  {"nombre":"Centro de Distribución de Red","descripcion":"Un patch panel bien instalado es la diferencia entre encontrar un problema en minutos o en horas.","servicio_asociado":"🔧 Instalamos racks completos con patch panels certificados, organizadores verticales, etiquetado profesional.","imagen":"/images/services/productos/infraestructura/1.2.png","caracteristicas":["Identifique cualquier punto en segundos","Agregue conexiones sin rediseñar","Blindaje contra interferencias"]},
  {"nombre":"Cableado Estructurado Certificado","descripcion":"No instalamos cables, construimos infraestructura. Cada punto con su certificación Fluke individual.","servicio_asociado":"🔧 Diseñamos e instalamos redes Cat5e, Cat6 y Cat6A con certificación punto por punto y garantía 25 años.","imagen":"/images/services/productos/infraestructura/1.3.png","caracteristicas":["Certificación individual Fluke","Garantía de 25 años","Cumplimiento TIA/EIA-568-C"]},
  {"nombre":"Switching de Alto Rendimiento","descripcion":"Su red necesita un cerebro que tome decisiones en microsegundos.","servicio_asociado":"🔧 Configuramos switching con VLANs, QoS, redundancia y monitoreo 24/7.","imagen":"/images/services/productos/infraestructura/1.4.png","caracteristicas":["Cero downtime con redundancia","Gestión remota segura","Arquitectura modular escalable"]},
  {"nombre":"Data Center Llave en Mano","descripcion":"Desde el piso técnico hasta el último cable, cumpliendo estándares internacionales.","servicio_asociado":"🔧 Construimos data centers completos: obra civil, climatización, energía, racks, cableado y seguridad.","imagen":"/images/services/productos/infraestructura/1.5.png","caracteristicas":["Diseño térmico optimizado","Acceso y mantenimiento simplificado","Cumplimiento TIA-942"]},
  {"nombre":"Radioenlaces Punto a Punto","descripcion":"Cuando el cable no es opción, el aire es el camino.","servicio_asociado":"🔧 Implementamos radioenlaces profesionales con estudio de factibilidad y SLA.","imagen":"/images/services/productos/infraestructura/1.6.png","caracteristicas":["Distancias de hasta 50 km","Velocidades de hasta 1 Gbps","99.99% de disponibilidad"]},
  {"nombre":"Certificación Profesional de Red","descripcion":"No confíe en funciona bien. Exija la prueba con equipamiento Fluke.","servicio_asociado":"🔧 Certificamos instalaciones con equipos Fluke DSX. Reportes PDF válidos para auditorías.","imagen":"/images/services/productos/infraestructura/1.7.png","caracteristicas":["Reporte PDF por cada punto","Válido para garantías de fabricante","Detecta fallas ocultas"]},
  {"nombre":"Gestión Profesional de Fibra Óptica","descripcion":"La fibra óptica es delicada y valiosa. Fusiones protegidas, identificación clara.","servicio_asociado":"🔧 Instalamos ODFs y realizamos fusiones certificadas con medición OTDR.","imagen":"/images/services/productos/infraestructura/1.8.png","caracteristicas":["Fusiones con pérdida < 0.1 dB","Expansión sin interrumpir servicio","Identificación por código de colores"]}
]'::json WHERE id = 101;

-- Service 102: Sistemas de Seguridad Electrónica (8 productos)
UPDATE "Servicios" SET "Productos" = '[
  {"nombre":"Central de Detección de Incendios","descripcion":"El corazón de su sistema de protección contra incendios. Centrales analógicas inteligentes.","servicio_asociado":"🔧 Instalamos y mantenemos centrales Notifier, Hochiki, Bosch con certificación IRAM.","imagen":"/images/services/productos/seguridad/2.1.png","caracteristicas":["Certificación IRAM/UL/FM","Programación personalizada","Monitoreo 24/7"]},
  {"nombre":"Detectores Inteligentes de Humo","descripcion":"Detectan el peligro antes de que sea visible. Tecnología óptica y térmica combinada.","servicio_asociado":"🔧 Instalamos detectores puntuales, lineales y de aspiración según cada necesidad.","imagen":"/images/services/productos/seguridad/2.2.png","caracteristicas":["Detección temprana","Bajo mantenimiento","Integración con BMS"]},
  {"nombre":"Sistema CCTV IP Profesional","descripcion":"Vigile su operación con resolución 4K y analítica de video integrada.","servicio_asociado":"🔧 Diseñamos e instalamos sistemas CCTV IP con NVR, cámaras y analítica.","imagen":"/images/services/productos/seguridad/2.3.png","caracteristicas":["Resolución hasta 4K","Analítica de video IA","Almacenamiento en la nube"]},
  {"nombre":"Control de Acceso Biométrico","descripcion":"Sepa quién entra, cuándo y a dónde. Huella, facial, tarjeta o combinado.","servicio_asociado":"🔧 Implementamos control de acceso con torniquetes, molinetes y puertas automatizadas.","imagen":"/images/services/productos/seguridad/2.4.png","caracteristicas":["Multi-tecnología","Registro de eventos","Integración con RRHH"]},
  {"nombre":"Sistema de Alarma Contra Intrusión","descripcion":"Protección perimetral e interior con sensores de última generación.","servicio_asociado":"🔧 Instalamos sistemas de alarma con monitoreo central 24/7.","imagen":"/images/services/productos/seguridad/2.5.png","caracteristicas":["Detección volumétrica","Contactos magnéticos","Sirenas y balizas"]},
  {"nombre":"Extinción Automática de Incendios","descripcion":"Cuando la detección no alcanza, la extinción actúa. Sistemas de agua, gas y espuma.","servicio_asociado":"🔧 Diseñamos sistemas de extinción para data centers, cocinas y áreas especiales.","imagen":"/images/services/productos/seguridad/2.6.png","caracteristicas":["Gas limpio FM-200","Rociadores automáticos","Sistemas de espuma"]}
]'::json WHERE id = 102;

-- Service 103: Telecomunicaciones (6 productos)
UPDATE "Servicios" SET "Productos" = '[
  {"nombre":"Central Telefónica IP","descripcion":"Comunique su empresa con tecnología VoIP de última generación.","servicio_asociado":"🔧 Instalamos centrales Asterisk, 3CX, Grandstream con configuración completa.","imagen":"/images/services/productos/telecomunicaciones/3.1.png","caracteristicas":["VoIP de alta calidad","Integración con móviles","Grabación de llamadas"]},
  {"nombre":"Telefonía Cloud","descripcion":"Sin inversión en hardware. Telefonía empresarial desde la nube.","servicio_asociado":"🔧 Configuramos y migramos su telefonía a servicios cloud con SLA.","imagen":"/images/services/productos/telecomunicaciones/3.2.png","caracteristicas":["Cero hardware","Escalabilidad infinita","Pago por uso"]},
  {"nombre":"Sistema de Voceo y PA","descripcion":"Comunicación masiva clara y profesional para instalaciones grandes.","servicio_asociado":"🔧 Instalamos sistemas de voceo con amplificadores, parlantes y micrófonos.","imagen":"/images/services/productos/telecomunicaciones/3.3.png","caracteristicas":["Zonas independientes","Integración con emergencias","Audio de alta fidelidad"]},
  {"nombre":"Integración Microsoft Teams","descripcion":"Unifique su comunicación con la plataforma líder de colaboración.","servicio_asociado":"🔧 Integramos telefonía tradicional con Microsoft Teams y Zoom.","imagen":"/images/services/productos/telecomunicaciones/3.4.png","caracteristicas":["Llamadas desde Teams","Presencia unificada","Colaboración en tiempo real"]},
  {"nombre":"Radiotroncalizado Digital","descripcion":"Comunicación de radio profesional para operaciones críticas.","servicio_asociado":"🔧 Implementamos sistemas DMR y TETRA para industria y emergencias.","imagen":"/images/services/productos/telecomunicaciones/3.5.png","caracteristicas":["Cobertura extendida","Encriptación de voz","GPS integrado"]},
  {"nombre":"Videocolaboración Profesional","descripcion":"Salas de reuniones equipadas con tecnología de videoconferencia.","servicio_asociado":"🔧 Diseñamos y equipamos salas con pantallas, cámaras y audio profesional.","imagen":"/images/services/productos/telecomunicaciones/3.6.png","caracteristicas":["4K Ultra HD","Audio inmersivo","Control táctil"]}
]'::json WHERE id = 103;

-- Service 104: Desarrollo de Software (6 productos)
UPDATE "Servicios" SET "Productos" = '[
  {"nombre":"Desarrollo Web Full Stack","descripcion":"Aplicaciones web modernas, responsivas y escalables.","servicio_asociado":"🔧 Desarrollamos con React, Vue, Node.js, Python según cada proyecto.","imagen":"/images/services/productos/desarrollo/4.1.png","caracteristicas":["Diseño responsive","APIs REST/GraphQL","Despliegue en la nube"]},
  {"nombre":"Aplicaciones Móviles","descripcion":"Apps nativas e híbridas para iOS y Android.","servicio_asociado":"🔧 Desarrollamos con Flutter, React Native o nativo según necesidad.","imagen":"/images/services/productos/desarrollo/4.2.png","caracteristicas":["iOS y Android","Notificaciones push","Offline first"]},
  {"nombre":"Sistemas ERP/CRM","descripcion":"Software de gestión empresarial a medida de su operación.","servicio_asociado":"🔧 Implementamos y personalizamos ERP/CRM sobre medida o plataformas existentes.","imagen":"/images/services/productos/desarrollo/4.3.png","caracteristicas":["Módulos integrados","Reportes avanzados","Multi-sucursal"]},
  {"nombre":"Automatización de Procesos","descripcion":"RPA y workflows para eliminar tareas repetitivas.","servicio_asociado":"🔧 Implementamos bots y automatizaciones con Power Automate, Zapier o desarrollo propio.","imagen":"/images/services/productos/desarrollo/4.4.png","caracteristicas":["ROI medible","Integración multi-sistema","Monitoreo en tiempo real"]},
  {"nombre":"Integración de Sistemas","descripcion":"Conectamos sus sistemas existentes para que hablen entre sí.","servicio_asociado":"🔧 Desarrollamos APIs, middleware y conectores para integrar cualquier sistema.","imagen":"/images/services/productos/desarrollo/4.5.png","caracteristicas":["APIs personalizadas","ETL de datos","Sincronización en tiempo real"]},
  {"nombre":"Business Intelligence","descripcion":"Dashboards y reportes que transforman datos en decisiones.","servicio_asociado":"🔧 Implementamos soluciones BI con Power BI, Tableau o desarrollo propio.","imagen":"/images/services/productos/desarrollo/4.6.png","caracteristicas":["Dashboards interactivos","KPIs en tiempo real","Alertas automáticas"]}
]'::json WHERE id = 104;

-- Service 105: Soporte TIC (6 productos)
UPDATE "Servicios" SET "Productos" = '[
  {"nombre":"Mesa de Ayuda 24/7","descripcion":"Soporte técnico disponible cuando lo necesite.","servicio_asociado":"🔧 Brindamos soporte nivel 1, 2 y 3 con SLA garantizado.","imagen":"/images/services/productos/soporte/5.1.png","caracteristicas":["Respuesta en 15 minutos","Soporte remoto y presencial","Tickets ilimitados"]},
  {"nombre":"Mantenimiento Preventivo","descripcion":"Anticipamos los problemas antes de que ocurran.","servicio_asociado":"🔧 Realizamos mantenimiento programado de servidores, redes y endpoints.","imagen":"/images/services/productos/soporte/5.2.png","caracteristicas":["Actualizaciones de seguridad","Limpieza de equipos","Reportes mensuales"]},
  {"nombre":"Monitoreo Proactivo","descripcion":"Vigilamos su infraestructura 24/7 con alertas inteligentes.","servicio_asociado":"🔧 Implementamos monitoreo con Zabbix, Nagios o herramientas enterprise.","imagen":"/images/services/productos/soporte/5.3.png","caracteristicas":["Detección temprana","Alertas automáticas","Dashboards en tiempo real"]},
  {"nombre":"Gestión de Incidentes ITIL","descripcion":"Procesos certificados para resolver y prevenir incidentes.","servicio_asociado":"🔧 Gestionamos incidentes con metodología ITIL y herramientas ITSM.","imagen":"/images/services/productos/soporte/5.4.png","caracteristicas":["Escalamiento definido","SLAs por prioridad","Análisis de causa raíz"]},
  {"nombre":"Backup y Recuperación","descripcion":"Sus datos protegidos y recuperables ante cualquier evento.","servicio_asociado":"🔧 Implementamos soluciones de backup local, en la nube e híbrido.","imagen":"/images/services/productos/soporte/5.5.png","caracteristicas":["Backup automático","Recuperación rápida","Pruebas periódicas"]},
  {"nombre":"Gestión de Activos IT","descripcion":"Control total de su inventario de hardware y software.","servicio_asociado":"🔧 Implementamos CMDB y control de licencias con herramientas especializadas.","imagen":"/images/services/productos/soporte/5.6.png","caracteristicas":["Inventario actualizado","Control de licencias","Ciclo de vida de activos"]}
]'::json WHERE id = 105;

-- Service 106: Consultoría IT (6 productos)
UPDATE "Servicios" SET "Productos" = '[
  {"nombre":"Auditoría de Infraestructura","descripcion":"Diagnóstico completo de su estado tecnológico actual.","servicio_asociado":"🔧 Realizamos auditorías de redes, servidores, seguridad y procesos IT.","imagen":"/images/services/productos/consultoria/6.1.png","caracteristicas":["Informe ejecutivo","Roadmap de mejoras","Priorización por impacto"]},
  {"nombre":"Planificación Estratégica IT","descripcion":"Alineamos la tecnología con los objetivos de negocio.","servicio_asociado":"🔧 Desarrollamos planes tecnológicos a 3-5 años con ROI proyectado.","imagen":"/images/services/productos/consultoria/6.2.png","caracteristicas":["Visión a largo plazo","Presupuesto detallado","Hitos medibles"]},
  {"nombre":"Arquitectura Empresarial","descripcion":"Diseñamos la estructura tecnológica óptima para su organización.","servicio_asociado":"🔧 Aplicamos frameworks TOGAF y Zachman para arquitectura enterprise.","imagen":"/images/services/productos/consultoria/6.3.png","caracteristicas":["Diagramas técnicos","Documentación completa","Gobernanza IT"]},
  {"nombre":"Evaluación de Riesgos","descripcion":"Identifique vulnerabilidades antes de que se conviertan en problemas.","servicio_asociado":"🔧 Realizamos análisis de riesgos con metodología ISO 27005.","imagen":"/images/services/productos/consultoria/6.4.png","caracteristicas":["Matriz de riesgos","Plan de mitigación","Monitoreo continuo"]},
  {"nombre":"Cumplimiento Normativo","descripcion":"Asegure el cumplimiento de regulaciones y estándares.","servicio_asociado":"🔧 Asesoramos en ISO 27001, PCI-DSS, GDPR y normativas locales.","imagen":"/images/services/productos/consultoria/6.5.png","caracteristicas":["Gap analysis","Plan de remediación","Auditorías de preparación"]},
  {"nombre":"Transformación Digital","descripcion":"Guiamos la evolución digital de su organización.","servicio_asociado":"🔧 Acompañamos proyectos de transformación con gestión del cambio.","imagen":"/images/services/productos/consultoria/6.6.png","caracteristicas":["Diagnóstico de madurez","Roadmap digital","Capacitación del equipo"]}
]'::json WHERE id = 106;

-- Verify updates
SELECT id, "Titulo", jsonb_array_length("Productos"::jsonb) as productos_count FROM "Servicios" WHERE id >= 101 AND id <= 106;

ENDOFSQL
