// Conceptual integrations, never actual client equipment or live control points.
export const SERVICE_URLS={
 Data:'https://www.ultimamilla.com.ar/servicios/101/infraestructura-de-redes',
 Fire:'https://www.ultimamilla.com.ar/servicios/107/sistemas-de-deteccion-y-alarma-de-incendios',
 Power:'https://www.ultimamilla.com.ar/servicios/108/servicios-electricos-para-it',
 Index:'https://www.ultimamilla.com.ar/servicios',
};
const instrument=(id,system,name,p,kind,measurement,why,source,extra)=>({id,system,name,p,kind,measurement,why,source,industrial:true,...(extra||{})});
const metric=(label,unit,base,amplitude,protocol)=>({label,unit,base,amplitude,protocol});
export function industrialInventory(sector){
 const hospital=sector==='hospital',winery=sector==='winery',prefix=hospital?'HOS':winery?'WIN':'AIR';
 const rack=hospital?[10.3,3.46,1.75]:winery?[12,2.45,1.8]:[10,3.45,1.8];
 const electrical=hospital?[18.6,7.74,1.65]:[22,4.5,1.6];
 const fire=hospital?[-13.5,15.69,1.55]:[15,1,1.5];
 const access=hospital?[.05,-2.2,1.32]:winery?[-15,1,1.2]:[15.7,13,1.2];
 const offset=(p,x,y,z)=>[p[0]+x,p[1]+y,z];
 // Caja de campo por sector: internación, manga, depósito. Troncal único al rack.
 const fbX=hospital?[6.8,12.8,1.5]:winery?[12.6,16.6,1.5]:[20.6,12.6,1.5];
 return [
 ...(!hospital&&!winery?[
 ...[[9.5,.7,1.25,'sala de red'],[20.5,.7,1.25,'sala eléctrica'],[15.1,12,1.25,'personal de embarque']].map(([x,y,z,zone],i)=>instrument(`AIR-DOOR-${i+1}`,'Security',`Puerta controlada · ${zone}`,[x,y,z],'door',metric('Estado de puerta','estado',0,0,'Lector / contacto / controlador DEMO'),'Conjunto ilustrativo con marco, hoja, cierrapuertas, lector y contacto. Cerrada en esta demostración; no representa una salida de emergencia ni acredita control aeroportuario.',access)),
 ...[[7,14,3.8,'embarque'],[-10,2,3.8,'check-in']].map(([x,y,z,zone],i)=>instrument(`AIR-WLAN-${i+1}`,'Telecom',`Wi-Fi · ${zone}`,[x,y,z],'ceiling-wifi',metric('Tráfico inalámbrico','Mb/s',42,5,'AP / Ethernet PoE DEMO'),'Punto de acceso con soporte elevado y retorno de red. Caudal sintético; no calcula cobertura, capacidad ni itinerancia.',rack)),
 ...[[10.8,4.8,2.7,'sala de red'],[21.5,4.8,2.7,'sala eléctrica'],[11,13,3.8,'embarque']].map(([x,y,z,zone],i)=>instrument(`AIR-SDI-${i+1}`,'Fire-detection',`Detector · ${zone}`,[x,y,z],'ceiling-detector',metric('Estado supervisado','estado',0,0,'Detección direccionable DEMO'),'Dispositivo de detección con base y cámara sensora diferenciadas. Selección de tecnología y cobertura pendientes de ingeniería; no se simula una alarma real.',fire)),
 instrument('AIR-MCP-GATE','Fire-detection','Pulsador manual · embarque',[14.3,12,1.3],'callpoint',metric('Estado de pulsador','estado',0,0,'Entrada supervisada DEMO'),'Aviso manual ilustrativo junto al sector de embarque. Sin activación de alarmas reales ni validación de distancia de evacuación.',fire),
 instrument('AIR-AV-GATE','Fire-detection','Avisador audiovisual · embarque',[14.3,12,2.35],'sounder',metric('Alimentación de aviso','V DC',24,.08,'Notificación supervisada DEMO'),'Separa la notificación de la detección: dispositivo audiovisual visible, sin sonido ni estrobos.',fire),
  instrument('AIR-IP-OPS','Telecom','Intercomunicador · acceso técnico',[8.65,.7,1.45],'intercom',metric('Tráfico de voz','Mb/s',.064,0,'SIP / RTP DEMO'),'Terminal de comunicación de personal con la operación. No establece llamadas ni registra audio.',rack),
  instrument('AIR-DOOR-4','Security','Puerta controlada · manga de embarque',[21.5,12,1.25],'door',metric('Estado de puerta','estado',0,0,'Lector / contacto / controlador DEMO'),'Conjunto ilustrativo con marco, hoja, cierrapuertas, lector y contacto junto a la manga. Cerrada en esta demostración; no representa una salida de emergencia ni acredita control aeroportuario.',fbX),
  instrument('AIR-WLAN-3','Telecom','Wi-Fi · manga',[20,13,3.8],'ceiling-wifi',metric('Tráfico inalámbrico','Mb/s',38,5,'AP / Ethernet PoE DEMO'),'Punto de acceso con soporte elevado y retorno de red en zona de embarque. Caudal sintético; no calcula cobertura, capacidad ni itinerancia.',fbX),
  instrument('AIR-SDI-4','Fire-detection','Detector · manga',[22,13,3.8],'ceiling-detector',metric('Estado supervisado','estado',0,0,'Detección direccionable DEMO'),'Dispositivo de detección con base y cámara sensora diferenciadas sobre la manga. Selección de tecnología y cobertura pendientes de ingeniería; no se simula una alarma real.',fire),
  instrument('AIR-METER-NET','Power','Analizador de red · sala de red',offset(rack,-.9,-.4,1.65),'meter',metric('Tensión de alimentación','V',230,1.4,'Modbus TCP / DEMO'),'Segundo punto de medida ilustrativo junto al rack de distribución. No representa un tablero aprobado.',rack),
  instrument('AIR-LEAK-PWR','Data','Detección de agua · sala eléctrica',offset(electrical,.7,.3,.15),'contact',metric('Presencia de agua','estado',0,0,'Contacto seco / gateway DEMO'),'Punto ilustrativo próximo a la sala eléctrica. Estado seco simulado, sin sensores conectados.',electrical),
  instrument('AIR-CONTACT-GATE','Security','Contacto · puerta de manga',[21.76,12.05,1.6],'contact',metric('Apertura del acceso','estado',0,0,'Entrada digital DEMO'),'Distingue el estado de la puerta de manga de la autorización del lector. Normal cerrado simulado, sin credenciales reales.',fbX),
 instrument('AIR-FB-GATE','Data','Caja de distribución · manga',fbX,'fieldbox',metric('Circuitos de campo','circuitos',8,0,'Cobre / DEMO'),'Concentra puerta, Wi-Fi y contacto de manga con un troncal único al rack. Detección de incendio mantiene home-run a central.',rack),
 instrument('AIR-BAT-1','Power','Banco de baterías · sala eléctrica',[21.2,5.4,0.7],'battery',metric('Autonomía ilustrativa','min',45,5,'BMS / DEMO'),'Banco ilustrativo de respaldo junto al UPS. No diagnostica baterías ni garantiza autonomías.',electrical),
 instrument('AIR-ATS-1','Power','Tablero de transferencia · sala eléctrica',[22.9,5.5,1.5],'transfer',metric('Carga respaldada','kW',8.5,.4,'Medidor / DEMO'),'Conmutación ilustrativa entre red y respaldo. Sin maniobras reales sobre la instalación.',electrical),
 instrument('AIR-DISH-1','Telecom','Radioenlace · terraza técnica',[10,4,4.9],'dish',metric('Nivel de recepción','dBm',-52,2,'Radio IP / DEMO'),'Enlace de contingencia ilustrativo sobre la sala de red. No promete cobertura ni usa espectro real.',rack,{base:4.2}),
 instrument('AIR-SURVEY-1','Data','Mesa de relevamiento · auditoría',[8.2,1.5,0],'survey',metric('Puntos relevados','puntos',24,0,'Planilla / DEMO'),'Mesa de trabajo de consultoría con planos y maletín. Representa relevamiento y auditoría, sin documentar instalación alguna.',rack),
 instrument('AIR-TOTEM-1','Software','Tótem de vuelos · embarque',[10,13,0],'totem',metric('Caras activas','pantallas',2,0,'CMS / DEMO'),'Tótem informativo ilustrativo de doble faz. Sin datos de vuelos reales.',rack),
 instrument('AIR-BEAM-1','Fire-detection','Detector lineal · hall',[-6,8,3.6],'beam',metric('Estado supervisado','estado',0,0,'Detección direccionable DEMO'),'Par emisor-receptor ilustrativo para grandes volúmenes. Tecnología y cobertura pendientes de ingeniería; no se simula una alarma real.',fire,{span:8}),
 instrument('AIR-BEACON-1','Fire-detection','Baliza exterior · curb',[8,-2,0],'beacon',metric('Circuito de notificación','V DC',24,.1,'Notificación supervisada DEMO'),'Notificación exterior con luz fija DEMO. Sin sonido ni destellos; implantación sujeta a ingeniería.',fire),
 instrument('AIR-BARRIER-1','Security','Barrera vehicular · acceso',[10.5,-3,0],'barrier',metric('Posición de brazo','estado',0,0,'Lazo / controlador DEMO'),'Barrera ilustrativa con brazo a franjas y lazo de presencia. No gestiona tránsito real.',access),
 instrument('AIR-POLECAM-1','CCTV','Cámara perimetral · plataforma',[24,8,0],'camera',metric('Video simulado','Mb/s',4,.3,'VMS / estado DEMO'),'Cámara perimetral ilustrativa en mástil con volumen de orientación. No calcula óptica ni zonas ciegas; sin video real.',[14.5,4,1.4]),
 instrument('AIR-PIR-1','Security','PIR · control',[-2,8,2.3],'pir',metric('Detección de movimiento','estado',0,0,'Entrada digital DEMO'),'Detector volumétrico ilustrativo de ambiente. Sin verificación de cobertura ni integración a alarma real.',access),
 instrument('AIR-ALARM-1','Security','Panel de alarma · sala de red',[9.0,3.0,1.6],'alarm-panel',metric('Zonas supervisadas','zonas',4,0,'Teclado / DEMO'),'Panel ilustrativo con teclado y zonas junto al rack. No arma ni desarma sistemas reales.',access),
  ]:[]),
  ...(hospital?[
  ...[[2.5,-2.2,1.25,'acceso principal'],[7.5,12,1.25,'personal de internación']].map(([x,y,z,zone],i)=>instrument(`HOS-DOOR-${i+1}`,'Security',`Puerta controlada · ${zone}`,[x,y,z],'door',metric('Estado de puerta','estado',0,0,'Lector / contacto / controlador DEMO'),'Conjunto ilustrativo con marco, hoja, cierrapuertas, lector y contacto. Cerrada en esta demostración; no representa una salida de emergencia ni acredita control clínico.',(i===1?fbX:access))),
  ...[[0,7,3.0,'pasillo'],[0,13,3.0,'internación']].map(([x,y,z,zone],i)=>instrument(`HOS-WLAN-${i+1}`,'Telecom',`Wi-Fi · ${zone}`,[x,y,z],'ceiling-wifi',metric('Tráfico inalámbrico','Mb/s',38,5,'AP / Ethernet PoE DEMO'),'Punto de acceso con soporte elevado y retorno de red. Caudal sintético; no calcula cobertura, capacidad ni itinerancia.',(i===1?fbX:rack))),
  ...[[-6,7,3.1,'pasillo'],[0,13,3.1,'internación']].map(([x,y,z,zone],i)=>instrument(`HOS-SDI-${i+1}`,'Fire-detection',`Detector · ${zone}`,[x,y,z],'ceiling-detector',metric('Estado supervisado','estado',0,0,'Detección direccionable DEMO'),'Dispositivo de detección con base y cámara sensora diferenciadas. Selección de tecnología y cobertura pendientes de ingeniería; no se simula una alarma real.',fire)),
  instrument('HOS-IP-OPS','Telecom','Intercomunicador · acceso técnico',[1.0,-2.2,1.45],'intercom',metric('Tráfico de voz','Mb/s',.064,0,'SIP / RTP DEMO'),'Terminal de comunicación del personal con la operación. No establece llamadas ni registra audio.',rack),
  instrument('HOS-TH-WARD','Data','Ambiente de internación · temperatura y humedad',[6.0,13.5,1.65],'environment',metric('Temperatura de sala','°C',22,1.0,'SNMP / gateway DEMO'),'Sensor ambiental ilustrativo de sala de internación. Ubicación y umbrales orientativos, sin criterio clínico.',fbX),
 instrument('HOS-FB-WARD','Data','Caja de distribución · internación',fbX,'fieldbox',metric('Circuitos de campo','circuitos',8,0,'Cobre / DEMO'),'Concentra puerta, Wi-Fi y ambiente de internación con un troncal único al rack. No empalma fibra; el ODF sigue en el rack.',rack),
 instrument('HOS-BAT-1','Power','Banco de baterías · sala eléctrica',[17.7,8.7,0.7],'battery',metric('Autonomía ilustrativa','min',45,5,'BMS / DEMO'),'Banco ilustrativo de respaldo junto al UPS. No diagnostica baterías ni garantiza autonomías.',electrical),
 instrument('HOS-ATS-1','Power','Tablero de transferencia · sala eléctrica',[19.3,7.0,1.5],'transfer',metric('Carga respaldada','kW',8.5,.4,'Medidor / DEMO'),'Conmutación ilustrativa entre red y respaldo. Sin maniobras reales sobre la instalación.',electrical),
 instrument('HOS-DISH-1','Telecom','Radioenlace · respaldo',[19.5,7.9,4.0],'dish',metric('Nivel de recepción','dBm',-52,2,'Radio IP / DEMO'),'Enlace de contingencia ilustrativo hacia la red. No promete cobertura ni usa espectro real.',rack,{base:3.4}),
 instrument('HOS-SURVEY-1','Data','Mesa de relevamiento · auditoría',[-3.5,4.0,0],'survey',metric('Puntos relevados','puntos',24,0,'Planilla / DEMO'),'Mesa de trabajo de consultoría con planos y maletín. Representa relevamiento y auditoría, sin documentar instalación alguna.',rack),
 instrument('HOS-NOC-1','Software','Muro NOC · SLA',[-2,2.0,2.0],'noc-wall',metric('Incidentes DEMO','eventos',2,1,'Mesa / DEMO'),'Tablero ilustrativo de monitoreo y SLA con un aviso DEMO activo. Sin conexión a sistemas reales.',rack),
 instrument('HOS-TOTEM-1','Software','Tótem de turnos · hall',[3.5,-1.5,0],'totem',metric('Caras activas','pantallas',2,0,'CMS / DEMO'),'Tótem informativo ilustrativo de doble faz. Sin datos de pacientes ni contenido real.',rack),
 instrument('HOS-PIR-1','Security','PIR · pasillo',[-6,6.8,2.3],'pir',metric('Detección de movimiento','estado',0,0,'Entrada digital DEMO'),'Detector volumétrico ilustrativo de ambiente. Sin verificación de cobertura ni integración a alarma real.',access),
 instrument('HOS-ALARM-1','Security','Panel de alarma · sala técnica',[9.5,3.2,1.6],'alarm-panel',metric('Zonas supervisadas','zonas',4,0,'Teclado / DEMO'),'Panel ilustrativo con teclado y zonas. No arma ni desarma sistemas reales.',access),
 instrument('HOS-POLECAM-1','CCTV','Cámara perimetral · parking',[.05,-6,0],'camera',metric('Video simulado','Mb/s',4,.3,'VMS / estado DEMO'),'Cámara perimetral ilustrativa en mástil con volumen de orientación. No calcula óptica ni zonas ciegas; sin video real.',[17.5,12.64,1.4]),
  ]:[]),
 instrument(`${prefix}-BAT-T`,'Power','Temperatura del respaldo eléctrico',offset(electrical,-.8,.1,.6),'environment',metric('Temperatura de gabinete','°C',26,1.1,'Sensor / gateway DEMO'),'Supervisión térmica ilustrativa de un gabinete de respaldo. No diagnostica baterías ni define límites de seguridad.',electrical),
 instrument(`${prefix}-LEAK`,'Data','Detección de agua · sala IT',offset(rack,-.7,.25,.15),'contact',metric('Presencia de agua','estado',0,0,'Contacto seco / gateway DEMO'),'Punto ilustrativo de detección de agua próximo al rack. Estado seco simulado, sin sensores conectados.',rack),
  ...(winery?[
  ...[[-13,1,1.25,'recepción'],[13.5,16,1.25,'depósito y despacho']].map(([x,y,z,zone],i)=>instrument(`WIN-DOOR-${i+1}`,'Security',`Puerta controlada · ${zone}`,[x,y,z],'door',metric('Estado de puerta','estado',0,0,'Lector / contacto / controlador DEMO'),'Conjunto ilustrativo con marco, hoja, cierrapuertas, lector y contacto. Cerrada en esta demostración; no representa una salida de emergencia ni acredita control de planta.',(i===1?fbX:access))),
  ...[[-8,11,4.8,'nave de tanques'],[12,16,4.8,'depósito']].map(([x,y,z,zone],i)=>instrument(`WIN-WLAN-${i+1}`,'Telecom',`Wi-Fi · ${zone}`,[x,y,z],'ceiling-wifi',metric('Tráfico inalámbrico','Mb/s',36,5,'AP / Ethernet PoE DEMO'),'Punto de acceso con soporte elevado y retorno de red en nave industrial. Caudal sintético; no calcula cobertura, capacidad ni itinerancia.',(i===1?fbX:rack))),
  ...[[-4,11,4.9,'nave de tanques'],[12,17,4.9,'depósito']].map(([x,y,z,zone],i)=>instrument(`WIN-SDI-${i+1}`,'Fire-detection',`Detector · ${zone}`,[x,y,z],'ceiling-detector',metric('Estado supervisado','estado',0,0,'Detección direccionable DEMO'),'Dispositivo de detección con base y cámara sensora diferenciadas en nave industrial. Selección de tecnología y cobertura pendientes de ingeniería; no se simula una alarma real.',fire)),
  instrument('WIN-IP-OPS','Telecom','Intercomunicador · operación',[11.5,3,1.45],'intercom',metric('Tráfico de voz','Mb/s',.064,0,'SIP / RTP DEMO'),'Terminal de comunicación entre recepción, operación y despacho. No establece llamadas ni registra audio.',rack),
 instrument('WIN-FB-DEP','Data','Caja de distribución · depósito',fbX,'fieldbox',metric('Circuitos de campo','circuitos',8,0,'Cobre / DEMO'),'Concentra puerta y Wi-Fi de depósito con un troncal único al rack. Detección de incendio mantiene home-run a central.',rack),
 instrument('WIN-BAT-1','Power','Banco de baterías · sala eléctrica',[21.2,5.4,0.7],'battery',metric('Autonomía ilustrativa','min',45,5,'BMS / DEMO'),'Banco ilustrativo de respaldo junto al UPS. No diagnostica baterías ni garantiza autonomías.',electrical),
 instrument('WIN-ATS-1','Power','Tablero de transferencia · sala eléctrica',[22.9,5.5,1.5],'transfer',metric('Carga respaldada','kW',8.5,.4,'Medidor / DEMO'),'Conmutación ilustrativa entre red y respaldo. Sin maniobras reales sobre la instalación.',electrical),
 instrument('WIN-DISH-1','Telecom','Radioenlace · operación',[16.5,1,3.0],'dish',metric('Nivel de recepción','dBm',-52,2,'Radio IP / DEMO'),'Enlace de contingencia ilustrativo para la operación. No promete cobertura ni usa espectro real.',rack,{base:0}),
 instrument('WIN-TOTEM-1','Software','Tótem de trazabilidad · recepción',[-12,5.5,0],'totem',metric('Caras activas','pantallas',2,0,'CMS / DEMO'),'Tótem informativo ilustrativo de doble faz. Sin datos de producción reales.',rack),
 instrument('WIN-LEVEL-1','Software','Nivel de tanque · integración propuesta',[-4,7.88,2.6],'level',metric('Nivel de proceso','%',62,3,'Transmisor / gateway DEMO'),'Transmisor de nivel ilustrativo, propuesto como integración con software. No acredita automatización de esta bodega ni controla proceso alguno.',[-4,7.88,.3]),
 instrument('WIN-BEAM-1','Fire-detection','Detector lineal · nave',[-10,11,4.5],'beam',metric('Estado supervisado','estado',0,0,'Detección direccionable DEMO'),'Par emisor-receptor ilustrativo para la nave de tanques. Tecnología y cobertura pendientes de ingeniería; no se simula una alarma real.',fire,{span:6}),
 instrument('WIN-BEACON-1','Fire-detection','Baliza exterior · despacho',[14.5,18.5,0],'beacon',metric('Circuito de notificación','V DC',24,.1,'Notificación supervisada DEMO'),'Notificación exterior con luz fija DEMO. Sin sonido ni destellos; implantación sujeta a ingeniería.',fire),
 instrument('WIN-BARRIER-1','Security','Barrera vehicular · portón',[-16,4,0],'barrier',metric('Posición de brazo','estado',0,0,'Lazo / controlador DEMO'),'Barrera ilustrativa de portón con brazo a franjas. No gestiona tránsito real.',access),
 instrument('WIN-POLECAM-1','CCTV','Cámara perimetral · depósito',[16,20,0],'camera',metric('Video simulado','Mb/s',4,.3,'VMS / estado DEMO'),'Cámara perimetral ilustrativa en mástil con volumen de orientación. No calcula óptica ni zonas ciegas; sin video real.',[14,3,1.4]),
 instrument('WIN-PIR-1','Security','PIR · depósito',[14.5,16,2.3],'pir',metric('Detección de movimiento','estado',0,0,'Entrada digital DEMO'),'Detector volumétrico ilustrativo de ambiente. Sin verificación de cobertura ni integración a alarma real.',access),
  instrument('WIN-BARREL-4','Software','Tonel 4 · temperatura ilustrativa',[-6,18.6,1.55],'barrel',metric('Temperatura de crianza','°C',16.9,.2,'Sonda / gateway DEMO'),'Sonda ilustrativa de temperatura en tonel. Instalación sanitaria, calibración y pertinencia enológica pendientes de proyecto; no gobierna el proceso.',[-6,18.6,.15]),
  ]:[]),
  ...(winery?[...[-12,-10,-8].map((x,i)=>instrument(`WIN-BARREL-${i+1}`,'Software',`Tonel ${i+1} · temperatura ilustrativa`,[x,18.6,1.55],'barrel',metric('Temperatura de crianza','°C',16+i*.3,.2,'Sonda / gateway DEMO'),'Sonda ilustrativa de temperatura en tonel. Instalación sanitaria, calibración y pertinencia enológica pendientes de proyecto; no gobierna el proceso.',[x,18.6,.15])),instrument('WIN-CELLAR-RH','Software','Ambiente de crianza · humedad',[-14,18,1.65],'environment',metric('Humedad relativa','% HR',70,2,'Sensor ambiental / DEMO'),'Condiciones ambientales ilustrativas del área de toneles, sin recomendaciones de conservación ni datos reales.',[-14,18,.15])]:[]),
 instrument(`${prefix}-TH`,'Data','Ambiente del rack · temperatura y humedad',offset(rack,-.42,.12,1.65),'environment',metric('Temperatura de admisión','°C',23,1.2,'SNMP / gateway DEMO'),'Sensor ambiental del rack: integra temperatura y humedad al monitoreo. Ubicación y umbrales ilustrativos.',rack),
 instrument(`${prefix}-PDU`,'Power','PDU medida · distribución del rack',offset(rack,.42,.12,1.1),'pdu',metric('Potencia de cargas IT','kW',1.8,.16,'Medición IP / DEMO'),'La PDU distribuye energía dentro del rack y permite observar la carga; no se confunde con un switch.',electrical),
 instrument(`${prefix}-OPT`,'Data','ODF · supervisión del enlace óptico',offset(rack,-.42,.12,1.3),'optical',metric('Potencia óptica recibida','dBm',-5.8,.12,'DOM del transceptor / DEMO'),'Terminación óptica integrada al rack. La lectura representa supervisión del transceptor, no una certificación OTDR.',rack),
 instrument(`${prefix}-METER`,'Power','Analizador de red · tablero IT',offset(electrical,-.48,-.2,1.65),'meter',metric('Tensión de alimentación','V',230,1.4,'Modbus TCP / DEMO'),'Tensión, frecuencia y carga ilustrativas para supervisar la alimentación IT. No representa un tablero aprobado.',electrical),
 instrument(`${prefix}-IO`,'Software','Gateway de telemetría · entradas y eventos',offset(electrical,-1,-.2,1.3),'gateway',metric('Muestras integradas','muestras/s',8,1,'Gateway / API local DEMO'),'Concentra señales de sensores para software y NOC. Integración propuesta; no controla equipos reales.',rack),
 instrument(`${prefix}-CALL`,'Fire-detection','Pulsador manual de alarma',offset(fire,-.45,0,1.3),'callpoint',metric('Estado supervisado','estado',0,0,'Circuito supervisado DEMO'),'Permite comunicar manualmente una condición de alarma. El visor sólo muestra estado normal sintético; no dispara ninguna acción.',fire),
 instrument(`${prefix}-SOUNDER`,'Fire-detection','Avisador audiovisual',offset(fire,-.45,0,2.35),'sounder',metric('Circuito de notificación','V DC',24,.1,'Notificación supervisada DEMO'),'Hace visible la función de notificación del SDI. Sin sirena ni destellos reales; implantación sujeta a ingeniería.',fire),
 instrument(`${prefix}-FIO`,'Fire-detection','Módulo de monitoreo e integración',offset(fire,.45,0,1.55),'gateway',metric('Entradas supervisadas','entradas',4,0,'Módulo de entrada / DEMO'),'Representa la interfaz entre la central y contactos de otros sistemas. No ejecuta supresión ni maniobras de emergencia.',fire),
 instrument(`${prefix}-CONTACT`,'Security','Contacto de acceso · estado de apertura',offset(access,.26,.05,1.6),'contact',metric('Apertura del acceso','estado',0,0,'Entrada digital DEMO'),'Distingue el estado de una puerta de la autorización del lector. Normal cerrado simulado, sin credenciales reales.',access),
 instrument(`${prefix}-WIFI`,'Telecom','Gateway inalámbrico · enlace de supervisión',offset(rack,.42,.12,2.15),'radio',metric('Señal de enlace','dBm',-54,2,'Radio IP / DEMO'),'Enlace ilustrativo para supervisión y continuidad. No promete cobertura ni usa un canal real de la instalación.',rack),
 instrument(`${prefix}-VIDEO`,'CCTV','Supervisión de grabación · nodo de salud',offset(hospital?[17.5,12.64,1.4]:winery?[14,3,1.4]:[14.5,4,1.4],-.4,0,1.4),'gateway',metric('Flujo agregado de video','Mb/s',20,1.5,'VMS / estado DEMO'),'Integra disponibilidad del grabador y flujo de cámaras al puesto de operación. No transmite imágenes de clientes.',hospital?[17.5,12.64,1.4]:winery?[14,3,1.4]:[14.5,4,1.4]),
 ...(winery?[instrument('WIN-TANK-T','Software','Temperatura de tanque · integración propuesta',[-8,7.88,2.35],'probe',metric('Temperatura de proceso','°C',18,.35,'Transmisor / gateway DEMO'),'Sensor de proceso ilustrativo, propuesto como integración con software. No acredita automatización de esta bodega ni controla fermentación.',[-8,7.88,.3])]:[]),
 ];
}
