version: '3'
services:
  database:
    image: postgres:15-alpine
    container_name: directus-admin-database-1
    restart: unless-stopped
    environment:
      POSTGRES_DB: directus
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - directus_db_data:/var/lib/postgresql/data
    networks:
      - fumbling-field_umbot-network

  directus-app:
    image: directus/directus:latest
    container_name: directus-admin-directus-app-1
    restart: unless-stopped
    environment:
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}
      DB_CLIENT: 'pg'
      DB_HOST: 'directus-admin-database-1'
      DB_PORT: '5432'
      DB_USER: 'directus'
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DATABASE: 'directus'
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      PUBLIC_URL: 'https://ultimamilla.com.ar'
      ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION: '8000'
      ASSETS_TRANSFORM_MAX_MAP_SIZE: '500mp'
    ports:
      - "8055:8055"
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    depends_on:
      - database
    networks:
      - fumbling-field_umbot-network

networks:
  fumbling-field_umbot-network:
    external: true

volumes:
  directus_db_data:
