networks:
  licitometro_default:
    external: true

services:
  directus-app:
    image: directus/directus:latest
    restart: unless-stopped
    environment:
      KEY: 12345678901234567890123456789012
      SECRET: S3cr3tK3yForDirectusConfig2025!!
      DB_CLIENT: pg
      DB_HOST: licitometro-db-1
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_DATABASE: mydatabase
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: adminpassword
    ports:
      - "8055:8055"
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    networks:
      - licitometro_default
