version: '3'
services:
  directus-app:
    image: directus/directus:latest
    restart: unless-stopped
    environment:
      KEY: '1.2345678901234567e+31'
      SECRET: 'S3cr3tK3yForDirectusConfig2025sshpass -p 'gsiB%s@0yD' ssh -o StrictHostKeyChecking=no root@23.105.176.45 cat /root/fumbling-field/directus-admin/docker-compose.yml'
      DB_CLIENT: 'pg'
      DB_HOST: 'umbot-postgres-prod'
      DB_PORT: '5432'
      DB_USER: 'directus'
      DB_PASSWORD: 'umbot_directus_2025!'
      DB_DATABASE: 'directus'
      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'adminpassword'
      PUBLIC_URL: 'https://www.ultimamilla.com.ar/admin'
      ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION: '8000'
      ASSETS_TRANSFORM_MAX_MAP_SIZE: '500mp'
    ports:
      - "8055:8055"
    volumes:
      - ../uploads:/directus/uploads
      - ./extensions:/directus/extensions
    networks:
      - fumbling-field_umbot-network

networks:
  fumbling-field_umbot-network:
    external: true
